package bridges

import (
	"encoding/json"
	"os"
	"testing"

	"github.com/digitallysavvy/go-ai/pkg/harness"
)

// bridgeIdentityFixture mirrors one entry of testdata/identity_fixtures.json,
// generated by testdata/gen_bridge_identity_fixtures.mjs from the TS
// `hashHarnessBootstrap` algorithm (see pkg/harness/bootstrap.go's
// HashHarnessBootstrap doc comment for the shared algorithm description).
type bridgeIdentityFixture struct {
	HarnessID    string                     `json:"harnessId"`
	BootstrapDir string                     `json:"bootstrapDir"`
	FileNames    []string                   `json:"fileNames"`
	Commands     []harness.BootstrapCommand `json:"commands"`
	Identity     string                     `json:"identity"`
}

// TestBridgeBootstrapIdentityMatchesTS is the "bootstrap identity computed
// from these files matches TS" test called for by the WG6 task: it builds
// each adapter's real bootstrap.Bootstrap recipe (same harnessId,
// bootstrapDir, file paths and commands as the adapter's own
// `*-bootstrap.ts`) using the bytes embedded in this package, feeds it
// through pkg/harness's HashHarnessBootstrap (the Go port of TS
// `hashHarnessBootstrap`), and checks the result against an identity
// independently computed by a Node script running the TS algorithm over the
// same bytes.
//
// A pass proves two things at once: the embedded bytes are exactly what a TS
// host would have embedded (any drift would change the identity), and the Go
// hashing implementation agrees with TS bit-for-bit on real (not synthetic)
// recipe content -- so a session bootstrapped by one host can be resumed by
// the other.
func TestBridgeBootstrapIdentityMatchesTS(t *testing.T) {
	data, err := os.ReadFile("testdata/identity_fixtures.json")
	if err != nil {
		t.Fatalf("reading fixtures: %v", err)
	}
	var fixtures map[string]bridgeIdentityFixture
	if err := json.Unmarshal(data, &fixtures); err != nil {
		t.Fatalf("parsing fixtures: %v", err)
	}
	if len(fixtures) == 0 {
		t.Fatal("no fixtures found")
	}

	for adapterName, fx := range fixtures {
		fx := fx
		t.Run(adapterName, func(t *testing.T) {
			files, err := Files(Adapter(adapterName))
			if err != nil {
				t.Fatalf("Files(%q): %v", adapterName, err)
			}

			recipe := harness.Bootstrap{
				HarnessID:    fx.HarnessID,
				BootstrapDir: fx.BootstrapDir,
				Commands:     fx.Commands,
			}
			for _, name := range fx.FileNames {
				content, ok := files[name]
				if !ok {
					t.Fatalf("adapter %q: fixture references embedded file %q which does not exist", adapterName, name)
				}
				recipe.Files = append(recipe.Files, harness.BootstrapFile{
					Path:    fx.BootstrapDir + "/" + name,
					Content: string(content),
				})
			}

			got := harness.HashHarnessBootstrap(recipe)
			if got != fx.Identity {
				t.Errorf("adapter %q: Go identity %s != TS-computed identity %s", adapterName, got, fx.Identity)
			}
		})
	}
}
