// Code generated by internal/gen from ai/packages/gateway/src/gateway-*-model-settings.ts; DO NOT EDIT.

package gateway

// Gateway model ID types mirror the TypeScript AI SDK Gateway*ModelId unions.
// Each TS union is open-ended (`| (string & {})`), so any string converts to
// these types; the constants below are the suggested IDs.
type (
	// GatewayLanguageModelID mirrors TS GatewayModelId.
	GatewayLanguageModelID string
	// GatewayEmbeddingModelID mirrors TS GatewayEmbeddingModelId.
	GatewayEmbeddingModelID string
	// GatewayImageModelID mirrors TS GatewayImageModelId.
	GatewayImageModelID string
	// GatewayVideoModelID mirrors TS GatewayVideoModelId.
	GatewayVideoModelID string
	// GatewayRerankingModelID mirrors TS GatewayRerankingModelId.
	GatewayRerankingModelID string
	// GatewaySpeechModelID mirrors TS GatewaySpeechModelId.
	GatewaySpeechModelID string
	// GatewayTranscriptionModelID mirrors TS GatewayTranscriptionModelId.
	GatewayTranscriptionModelID string
	// GatewayRealtimeModelID mirrors TS GatewayRealtimeModelId.
	GatewayRealtimeModelID string
	// GatewayEvaluationModelID mirrors TS GatewayEvaluationModelId.
	GatewayEvaluationModelID string
)

// GatewayLanguageModelID constants mirror gateway-language-model-settings.ts.
const (
	GatewayLanguageModelAlibabaQwen314b                  GatewayLanguageModelID = "alibaba/qwen-3-14b"
	GatewayLanguageModelAlibabaQwen3235b                 GatewayLanguageModelID = "alibaba/qwen-3-235b"
	GatewayLanguageModelAlibabaQwen330b                  GatewayLanguageModelID = "alibaba/qwen-3-30b"
	GatewayLanguageModelAlibabaQwen332b                  GatewayLanguageModelID = "alibaba/qwen-3-32b"
	GatewayLanguageModelAlibabaQwen36MaxPreview          GatewayLanguageModelID = "alibaba/qwen-3.6-max-preview"
	GatewayLanguageModelAlibabaQwen3235bA22bThinking     GatewayLanguageModelID = "alibaba/qwen3-235b-a22b-thinking"
	GatewayLanguageModelAlibabaQwen3Coder                GatewayLanguageModelID = "alibaba/qwen3-coder"
	GatewayLanguageModelAlibabaQwen3Coder30bA3b          GatewayLanguageModelID = "alibaba/qwen3-coder-30b-a3b"
	GatewayLanguageModelAlibabaQwen3CoderNext            GatewayLanguageModelID = "alibaba/qwen3-coder-next"
	GatewayLanguageModelAlibabaQwen3CoderPlus            GatewayLanguageModelID = "alibaba/qwen3-coder-plus"
	GatewayLanguageModelAlibabaQwen3Max                  GatewayLanguageModelID = "alibaba/qwen3-max"
	GatewayLanguageModelAlibabaQwen3MaxPreview           GatewayLanguageModelID = "alibaba/qwen3-max-preview"
	GatewayLanguageModelAlibabaQwen3MaxThinking          GatewayLanguageModelID = "alibaba/qwen3-max-thinking"
	GatewayLanguageModelAlibabaQwen3Next80bA3bInstruct   GatewayLanguageModelID = "alibaba/qwen3-next-80b-a3b-instruct"
	GatewayLanguageModelAlibabaQwen3Next80bA3bThinking   GatewayLanguageModelID = "alibaba/qwen3-next-80b-a3b-thinking"
	GatewayLanguageModelAlibabaQwen3Vl235bA22bInstruct   GatewayLanguageModelID = "alibaba/qwen3-vl-235b-a22b-instruct"
	GatewayLanguageModelAlibabaQwen3VlInstruct           GatewayLanguageModelID = "alibaba/qwen3-vl-instruct"
	GatewayLanguageModelAlibabaQwen3VlThinking           GatewayLanguageModelID = "alibaba/qwen3-vl-thinking"
	GatewayLanguageModelAlibabaQwen35Flash               GatewayLanguageModelID = "alibaba/qwen3.5-flash"
	GatewayLanguageModelAlibabaQwen35Plus                GatewayLanguageModelID = "alibaba/qwen3.5-plus"
	GatewayLanguageModelAlibabaQwen3627b                 GatewayLanguageModelID = "alibaba/qwen3.6-27b"
	GatewayLanguageModelAlibabaQwen36Plus                GatewayLanguageModelID = "alibaba/qwen3.6-plus"
	GatewayLanguageModelAlibabaQwen37Flash               GatewayLanguageModelID = "alibaba/qwen3.7-flash"
	GatewayLanguageModelAlibabaQwen37Max                 GatewayLanguageModelID = "alibaba/qwen3.7-max"
	GatewayLanguageModelAlibabaQwen37Plus                GatewayLanguageModelID = "alibaba/qwen3.7-plus"
	GatewayLanguageModelAlibabaQwen3824tA95b             GatewayLanguageModelID = "alibaba/qwen3.8-2.4t-a95b"
	GatewayLanguageModelAlibabaQwen3827b                 GatewayLanguageModelID = "alibaba/qwen3.8-27b"
	GatewayLanguageModelAlibabaQwen38Flash               GatewayLanguageModelID = "alibaba/qwen3.8-flash"
	GatewayLanguageModelAlibabaQwen38Max                 GatewayLanguageModelID = "alibaba/qwen3.8-max"
	GatewayLanguageModelAlibabaQwen38Max0902             GatewayLanguageModelID = "alibaba/qwen3.8-max-0902"
	GatewayLanguageModelAlibabaQwen38OmniFlash           GatewayLanguageModelID = "alibaba/qwen3.8-omni-flash"
	GatewayLanguageModelAmazonNova2Lite                  GatewayLanguageModelID = "amazon/nova-2-lite"
	GatewayLanguageModelAmazonNovaLite                   GatewayLanguageModelID = "amazon/nova-lite"
	GatewayLanguageModelAmazonNovaMicro                  GatewayLanguageModelID = "amazon/nova-micro"
	GatewayLanguageModelAmazonNovaPro                    GatewayLanguageModelID = "amazon/nova-pro"
	GatewayLanguageModelAnthropicClaude3Haiku            GatewayLanguageModelID = "anthropic/claude-3-haiku"
	GatewayLanguageModelAnthropicClaudeFable5            GatewayLanguageModelID = "anthropic/claude-fable-5"
	GatewayLanguageModelAnthropicClaudeFable51           GatewayLanguageModelID = "anthropic/claude-fable-5.1"
	GatewayLanguageModelAnthropicClaudeHaiku45           GatewayLanguageModelID = "anthropic/claude-haiku-4.5"
	GatewayLanguageModelAnthropicClaudeOpus4             GatewayLanguageModelID = "anthropic/claude-opus-4"
	GatewayLanguageModelAnthropicClaudeOpus45            GatewayLanguageModelID = "anthropic/claude-opus-4.5"
	GatewayLanguageModelAnthropicClaudeOpus46            GatewayLanguageModelID = "anthropic/claude-opus-4.6"
	GatewayLanguageModelAnthropicClaudeOpus47            GatewayLanguageModelID = "anthropic/claude-opus-4.7"
	GatewayLanguageModelAnthropicClaudeOpus48            GatewayLanguageModelID = "anthropic/claude-opus-4.8"
	GatewayLanguageModelAnthropicClaudeOpus48Fast        GatewayLanguageModelID = "anthropic/claude-opus-4.8-fast"
	GatewayLanguageModelAnthropicClaudeOpus5             GatewayLanguageModelID = "anthropic/claude-opus-5"
	GatewayLanguageModelAnthropicClaudeOpus5Fast         GatewayLanguageModelID = "anthropic/claude-opus-5-fast"
	GatewayLanguageModelAnthropicClaudeOpus55            GatewayLanguageModelID = "anthropic/claude-opus-5.5"
	GatewayLanguageModelAnthropicClaudeSonnet4           GatewayLanguageModelID = "anthropic/claude-sonnet-4"
	GatewayLanguageModelAnthropicClaudeSonnet45          GatewayLanguageModelID = "anthropic/claude-sonnet-4.5"
	GatewayLanguageModelAnthropicClaudeSonnet46          GatewayLanguageModelID = "anthropic/claude-sonnet-4.6"
	GatewayLanguageModelAnthropicClaudeSonnet5           GatewayLanguageModelID = "anthropic/claude-sonnet-5"
	GatewayLanguageModelAnthropicClaudeSonnet55          GatewayLanguageModelID = "anthropic/claude-sonnet-5.5"
	GatewayLanguageModelArceeAiTrinityLargeThinking      GatewayLanguageModelID = "arcee-ai/trinity-large-thinking"
	GatewayLanguageModelBytedanceSeed16                  GatewayLanguageModelID = "bytedance/seed-1.6"
	GatewayLanguageModelBytedanceSeed18                  GatewayLanguageModelID = "bytedance/seed-1.8"
	GatewayLanguageModelBytedanceSeed21Turbo             GatewayLanguageModelID = "bytedance/seed-2.1-turbo"
	GatewayLanguageModelCohereCommandA                   GatewayLanguageModelID = "cohere/command-a"
	GatewayLanguageModelDeepseekDeepseekR1               GatewayLanguageModelID = "deepseek/deepseek-r1"
	GatewayLanguageModelDeepseekDeepseekV31              GatewayLanguageModelID = "deepseek/deepseek-v3.1"
	GatewayLanguageModelDeepseekDeepseekV31Terminus      GatewayLanguageModelID = "deepseek/deepseek-v3.1-terminus"
	GatewayLanguageModelDeepseekDeepseekV32              GatewayLanguageModelID = "deepseek/deepseek-v3.2"
	GatewayLanguageModelDeepseekDeepseekV32Thinking      GatewayLanguageModelID = "deepseek/deepseek-v3.2-thinking"
	GatewayLanguageModelDeepseekDeepseekV4Flash          GatewayLanguageModelID = "deepseek/deepseek-v4-flash"
	GatewayLanguageModelDeepseekDeepseekV4Flash0731      GatewayLanguageModelID = "deepseek/deepseek-v4-flash-0731"
	GatewayLanguageModelDeepseekDeepseekV4FlashVisionExp GatewayLanguageModelID = "deepseek/deepseek-v4-flash-vision-exp"
	GatewayLanguageModelDeepseekDeepseekV4Pro            GatewayLanguageModelID = "deepseek/deepseek-v4-pro"
	GatewayLanguageModelDeepseekDeepseekV4Pro0813        GatewayLanguageModelID = "deepseek/deepseek-v4-pro-0813"
	GatewayLanguageModelDeepseekDeepseekV41Flash         GatewayLanguageModelID = "deepseek/deepseek-v4.1-flash"
	GatewayLanguageModelGoogleGemini25Flash              GatewayLanguageModelID = "google/gemini-2.5-flash"
	GatewayLanguageModelGoogleGemini25FlashImage         GatewayLanguageModelID = "google/gemini-2.5-flash-image"
	GatewayLanguageModelGoogleGemini25FlashLite          GatewayLanguageModelID = "google/gemini-2.5-flash-lite"
	GatewayLanguageModelGoogleGemini25Pro                GatewayLanguageModelID = "google/gemini-2.5-pro"
	GatewayLanguageModelGoogleGemini3Flash               GatewayLanguageModelID = "google/gemini-3-flash"
	GatewayLanguageModelGoogleGemini3ProImage            GatewayLanguageModelID = "google/gemini-3-pro-image"
	GatewayLanguageModelGoogleGemini31FlashImage         GatewayLanguageModelID = "google/gemini-3.1-flash-image"
	GatewayLanguageModelGoogleGemini31FlashImagePreview  GatewayLanguageModelID = "google/gemini-3.1-flash-image-preview"
	GatewayLanguageModelGoogleGemini31FlashLite          GatewayLanguageModelID = "google/gemini-3.1-flash-lite"
	GatewayLanguageModelGoogleGemini31FlashLiteImage     GatewayLanguageModelID = "google/gemini-3.1-flash-lite-image"
	GatewayLanguageModelGoogleGemini31ProPreview         GatewayLanguageModelID = "google/gemini-3.1-pro-preview"
	GatewayLanguageModelGoogleGemini35Flash              GatewayLanguageModelID = "google/gemini-3.5-flash"
	GatewayLanguageModelGoogleGemini35FlashLite          GatewayLanguageModelID = "google/gemini-3.5-flash-lite"
	GatewayLanguageModelGoogleGemini36Flash              GatewayLanguageModelID = "google/gemini-3.6-flash"
	GatewayLanguageModelGoogleGemini37Flash              GatewayLanguageModelID = "google/gemini-3.7-flash"
	GatewayLanguageModelGoogleGemini38Flash              GatewayLanguageModelID = "google/gemini-3.8-flash"
	GatewayLanguageModelGoogleGeminiOmniFlashPreview     GatewayLanguageModelID = "google/gemini-omni-flash-preview"
	GatewayLanguageModelGoogleGemma426bA4bIt             GatewayLanguageModelID = "google/gemma-4-26b-a4b-it"
	GatewayLanguageModelGoogleGemma431bIt                GatewayLanguageModelID = "google/gemma-4-31b-it"
	GatewayLanguageModelInceptionMercury2                GatewayLanguageModelID = "inception/mercury-2"
	GatewayLanguageModelInceptionMercury25               GatewayLanguageModelID = "inception/mercury-2.5"
	GatewayLanguageModelInceptionMercuryCoderSmall       GatewayLanguageModelID = "inception/mercury-coder-small"
	GatewayLanguageModelInclusionaiLing30Flash           GatewayLanguageModelID = "inclusionai/ling-3.0-flash"
	GatewayLanguageModelInclusionaiLing30FlashFin        GatewayLanguageModelID = "inclusionai/ling-3.0-flash-fin"
	GatewayLanguageModelInclusionaiLing30FlashFinFree    GatewayLanguageModelID = "inclusionai/ling-3.0-flash-fin-free"
	GatewayLanguageModelInclusionaiLing30FlashSante      GatewayLanguageModelID = "inclusionai/ling-3.0-flash-sante"
	GatewayLanguageModelInclusionaiLing30FlashSanteFree  GatewayLanguageModelID = "inclusionai/ling-3.0-flash-sante-free"
	GatewayLanguageModelInclusionaiLing30FlashVl         GatewayLanguageModelID = "inclusionai/ling-3.0-flash-vl"
	GatewayLanguageModelInclusionaiLing30FlashVlFree     GatewayLanguageModelID = "inclusionai/ling-3.0-flash-vl-free"
	GatewayLanguageModelInferenceNetSchematronV2Small    GatewayLanguageModelID = "inference-net/schematron-v2-small"
	GatewayLanguageModelInferenceNetSchematronV2Turbo    GatewayLanguageModelID = "inference-net/schematron-v2-turbo"
	GatewayLanguageModelInterfazeInterfazeBeta           GatewayLanguageModelID = "interfaze/interfaze-beta"
	GatewayLanguageModelMetaLlama3170b                   GatewayLanguageModelID = "meta/llama-3.1-70b"
	GatewayLanguageModelMetaLlama318b                    GatewayLanguageModelID = "meta/llama-3.1-8b"
	GatewayLanguageModelMetaLlama3370b                   GatewayLanguageModelID = "meta/llama-3.3-70b"
	GatewayLanguageModelMetaLlama4Maverick               GatewayLanguageModelID = "meta/llama-4-maverick"
	GatewayLanguageModelMetaLlama4Scout                  GatewayLanguageModelID = "meta/llama-4-scout"
	GatewayLanguageModelMetaMuseGlimmer30b               GatewayLanguageModelID = "meta/muse-glimmer-30b"
	GatewayLanguageModelMetaMuseSpark11                  GatewayLanguageModelID = "meta/muse-spark-1.1"
	GatewayLanguageModelMetaMuseSpark12                  GatewayLanguageModelID = "meta/muse-spark-1.2"
	GatewayLanguageModelMetaMuseSpark12Contributor       GatewayLanguageModelID = "meta/muse-spark-1.2-contributor"
	GatewayLanguageModelMetaMuseSpark13                  GatewayLanguageModelID = "meta/muse-spark-1.3"
	GatewayLanguageModelMetaMuseSpark13Contributor       GatewayLanguageModelID = "meta/muse-spark-1.3-contributor"
	GatewayLanguageModelMinimaxMinimaxM2                 GatewayLanguageModelID = "minimax/minimax-m2"
	GatewayLanguageModelMinimaxMinimaxM21                GatewayLanguageModelID = "minimax/minimax-m2.1"
	GatewayLanguageModelMinimaxMinimaxM21Lightning       GatewayLanguageModelID = "minimax/minimax-m2.1-lightning"
	GatewayLanguageModelMinimaxMinimaxM25                GatewayLanguageModelID = "minimax/minimax-m2.5"
	GatewayLanguageModelMinimaxMinimaxM25Highspeed       GatewayLanguageModelID = "minimax/minimax-m2.5-highspeed"
	GatewayLanguageModelMinimaxMinimaxM27                GatewayLanguageModelID = "minimax/minimax-m2.7"
	GatewayLanguageModelMinimaxMinimaxM27Highspeed       GatewayLanguageModelID = "minimax/minimax-m2.7-highspeed"
	GatewayLanguageModelMinimaxMinimaxM3                 GatewayLanguageModelID = "minimax/minimax-m3"
	GatewayLanguageModelMistralCodestral                 GatewayLanguageModelID = "mistral/codestral"
	GatewayLanguageModelMistralMinistral14b              GatewayLanguageModelID = "mistral/ministral-14b"
	GatewayLanguageModelMistralMinistral3b               GatewayLanguageModelID = "mistral/ministral-3b"
	GatewayLanguageModelMistralMinistral8b               GatewayLanguageModelID = "mistral/ministral-8b"
	GatewayLanguageModelMistralMistralLarge3             GatewayLanguageModelID = "mistral/mistral-large-3"
	GatewayLanguageModelMistralMistralMedium35           GatewayLanguageModelID = "mistral/mistral-medium-3.5"
	GatewayLanguageModelMistralMistralNemo               GatewayLanguageModelID = "mistral/mistral-nemo"
	GatewayLanguageModelMistralMistralSmall              GatewayLanguageModelID = "mistral/mistral-small"
	GatewayLanguageModelMixedbreadToast1                 GatewayLanguageModelID = "mixedbread/toast-1"
	GatewayLanguageModelMoonshotaiKimiK2                 GatewayLanguageModelID = "moonshotai/kimi-k2"
	GatewayLanguageModelMoonshotaiKimiK2Thinking         GatewayLanguageModelID = "moonshotai/kimi-k2-thinking"
	GatewayLanguageModelMoonshotaiKimiK25                GatewayLanguageModelID = "moonshotai/kimi-k2.5"
	GatewayLanguageModelMoonshotaiKimiK26                GatewayLanguageModelID = "moonshotai/kimi-k2.6"
	GatewayLanguageModelMoonshotaiKimiK27Code            GatewayLanguageModelID = "moonshotai/kimi-k2.7-code"
	GatewayLanguageModelMoonshotaiKimiK27CodeHighspeed   GatewayLanguageModelID = "moonshotai/kimi-k2.7-code-highspeed"
	GatewayLanguageModelMoonshotaiKimiK3                 GatewayLanguageModelID = "moonshotai/kimi-k3"
	GatewayLanguageModelMoonshotaiKimiK3Fast             GatewayLanguageModelID = "moonshotai/kimi-k3-fast"
	GatewayLanguageModelMorphMorphV3Fast                 GatewayLanguageModelID = "morph/morph-v3-fast"
	GatewayLanguageModelMorphMorphV3Large                GatewayLanguageModelID = "morph/morph-v3-large"
	GatewayLanguageModelNvidiaNemotron3Nano30bA3b        GatewayLanguageModelID = "nvidia/nemotron-3-nano-30b-a3b"
	GatewayLanguageModelNvidiaNemotron3Super120bA12b     GatewayLanguageModelID = "nvidia/nemotron-3-super-120b-a12b"
	GatewayLanguageModelNvidiaNemotron3Ultra550bA55b     GatewayLanguageModelID = "nvidia/nemotron-3-ultra-550b-a55b"
	GatewayLanguageModelNvidiaNemotron35Lightning        GatewayLanguageModelID = "nvidia/nemotron-3.5-lightning"
	GatewayLanguageModelNvidiaNemotronNano12bV2Vl        GatewayLanguageModelID = "nvidia/nemotron-nano-12b-v2-vl"
	GatewayLanguageModelNvidiaNemotronNano9bV2           GatewayLanguageModelID = "nvidia/nemotron-nano-9b-v2"
	GatewayLanguageModelOpenaiGpt35Turbo                 GatewayLanguageModelID = "openai/gpt-3.5-turbo"
	GatewayLanguageModelOpenaiGpt4Turbo                  GatewayLanguageModelID = "openai/gpt-4-turbo"
	GatewayLanguageModelOpenaiGpt41                      GatewayLanguageModelID = "openai/gpt-4.1"
	GatewayLanguageModelOpenaiGpt41Fast                  GatewayLanguageModelID = "openai/gpt-4.1-fast"
	GatewayLanguageModelOpenaiGpt41Mini                  GatewayLanguageModelID = "openai/gpt-4.1-mini"
	GatewayLanguageModelOpenaiGpt41MiniFast              GatewayLanguageModelID = "openai/gpt-4.1-mini-fast"
	GatewayLanguageModelOpenaiGpt41Nano                  GatewayLanguageModelID = "openai/gpt-4.1-nano"
	GatewayLanguageModelOpenaiGpt41NanoFast              GatewayLanguageModelID = "openai/gpt-4.1-nano-fast"
	GatewayLanguageModelOpenaiGpt4o                      GatewayLanguageModelID = "openai/gpt-4o"
	GatewayLanguageModelOpenaiGpt4oFast                  GatewayLanguageModelID = "openai/gpt-4o-fast"
	GatewayLanguageModelOpenaiGpt4oMini                  GatewayLanguageModelID = "openai/gpt-4o-mini"
	GatewayLanguageModelOpenaiGpt4oMiniFast              GatewayLanguageModelID = "openai/gpt-4o-mini-fast"
	GatewayLanguageModelOpenaiGpt5                       GatewayLanguageModelID = "openai/gpt-5"
	GatewayLanguageModelOpenaiGpt5Codex                  GatewayLanguageModelID = "openai/gpt-5-codex"
	GatewayLanguageModelOpenaiGpt5Fast                   GatewayLanguageModelID = "openai/gpt-5-fast"
	GatewayLanguageModelOpenaiGpt5Mini                   GatewayLanguageModelID = "openai/gpt-5-mini"
	GatewayLanguageModelOpenaiGpt5MiniFast               GatewayLanguageModelID = "openai/gpt-5-mini-fast"
	GatewayLanguageModelOpenaiGpt5Nano                   GatewayLanguageModelID = "openai/gpt-5-nano"
	GatewayLanguageModelOpenaiGpt5Pro                    GatewayLanguageModelID = "openai/gpt-5-pro"
	GatewayLanguageModelOpenaiGpt51Codex                 GatewayLanguageModelID = "openai/gpt-5.1-codex"
	GatewayLanguageModelOpenaiGpt51CodexMax              GatewayLanguageModelID = "openai/gpt-5.1-codex-max"
	GatewayLanguageModelOpenaiGpt51CodexMini             GatewayLanguageModelID = "openai/gpt-5.1-codex-mini"
	GatewayLanguageModelOpenaiGpt51Thinking              GatewayLanguageModelID = "openai/gpt-5.1-thinking"
	GatewayLanguageModelOpenaiGpt51ThinkingFast          GatewayLanguageModelID = "openai/gpt-5.1-thinking-fast"
	GatewayLanguageModelOpenaiGpt52                      GatewayLanguageModelID = "openai/gpt-5.2"
	GatewayLanguageModelOpenaiGpt52Codex                 GatewayLanguageModelID = "openai/gpt-5.2-codex"
	GatewayLanguageModelOpenaiGpt52Fast                  GatewayLanguageModelID = "openai/gpt-5.2-fast"
	GatewayLanguageModelOpenaiGpt52Pro                   GatewayLanguageModelID = "openai/gpt-5.2-pro"
	GatewayLanguageModelOpenaiGpt53Codex                 GatewayLanguageModelID = "openai/gpt-5.3-codex"
	GatewayLanguageModelOpenaiGpt53CodexFast             GatewayLanguageModelID = "openai/gpt-5.3-codex-fast"
	GatewayLanguageModelOpenaiGpt54                      GatewayLanguageModelID = "openai/gpt-5.4"
	GatewayLanguageModelOpenaiGpt54Fast                  GatewayLanguageModelID = "openai/gpt-5.4-fast"
	GatewayLanguageModelOpenaiGpt54Mini                  GatewayLanguageModelID = "openai/gpt-5.4-mini"
	GatewayLanguageModelOpenaiGpt54MiniFast              GatewayLanguageModelID = "openai/gpt-5.4-mini-fast"
	GatewayLanguageModelOpenaiGpt54Nano                  GatewayLanguageModelID = "openai/gpt-5.4-nano"
	GatewayLanguageModelOpenaiGpt54Pro                   GatewayLanguageModelID = "openai/gpt-5.4-pro"
	GatewayLanguageModelOpenaiGpt55                      GatewayLanguageModelID = "openai/gpt-5.5"
	GatewayLanguageModelOpenaiGpt55Fast                  GatewayLanguageModelID = "openai/gpt-5.5-fast"
	GatewayLanguageModelOpenaiGpt55Pro                   GatewayLanguageModelID = "openai/gpt-5.5-pro"
	GatewayLanguageModelOpenaiGpt56Luna                  GatewayLanguageModelID = "openai/gpt-5.6-luna"
	GatewayLanguageModelOpenaiGpt56LunaFast              GatewayLanguageModelID = "openai/gpt-5.6-luna-fast"
	GatewayLanguageModelOpenaiGpt56Sol                   GatewayLanguageModelID = "openai/gpt-5.6-sol"
	GatewayLanguageModelOpenaiGpt56SolFast               GatewayLanguageModelID = "openai/gpt-5.6-sol-fast"
	GatewayLanguageModelOpenaiGpt56Terra                 GatewayLanguageModelID = "openai/gpt-5.6-terra"
	GatewayLanguageModelOpenaiGpt56TerraFast             GatewayLanguageModelID = "openai/gpt-5.6-terra-fast"
	GatewayLanguageModelOpenaiGpt6Astra                  GatewayLanguageModelID = "openai/gpt-6-astra"
	GatewayLanguageModelOpenaiGpt6AstraFast              GatewayLanguageModelID = "openai/gpt-6-astra-fast"
	GatewayLanguageModelOpenaiGpt6Luna                   GatewayLanguageModelID = "openai/gpt-6-luna"
	GatewayLanguageModelOpenaiGpt6LunaFast               GatewayLanguageModelID = "openai/gpt-6-luna-fast"
	GatewayLanguageModelOpenaiGpt6Sol                    GatewayLanguageModelID = "openai/gpt-6-sol"
	GatewayLanguageModelOpenaiGpt6SolFast                GatewayLanguageModelID = "openai/gpt-6-sol-fast"
	GatewayLanguageModelOpenaiGptOss120b                 GatewayLanguageModelID = "openai/gpt-oss-120b"
	GatewayLanguageModelOpenaiGptOss20b                  GatewayLanguageModelID = "openai/gpt-oss-20b"
	GatewayLanguageModelOpenaiGptOssSafeguard120b        GatewayLanguageModelID = "openai/gpt-oss-safeguard-120b"
	GatewayLanguageModelOpenaiGptOssSafeguard20b         GatewayLanguageModelID = "openai/gpt-oss-safeguard-20b"
	GatewayLanguageModelOpenaiO1                         GatewayLanguageModelID = "openai/o1"
	GatewayLanguageModelOpenaiO3                         GatewayLanguageModelID = "openai/o3"
	GatewayLanguageModelOpenaiO3Fast                     GatewayLanguageModelID = "openai/o3-fast"
	GatewayLanguageModelOpenaiO3Mini                     GatewayLanguageModelID = "openai/o3-mini"
	GatewayLanguageModelOpenaiO3Pro                      GatewayLanguageModelID = "openai/o3-pro"
	GatewayLanguageModelOpenaiO4Mini                     GatewayLanguageModelID = "openai/o4-mini"
	GatewayLanguageModelOpenaiO4MiniFast                 GatewayLanguageModelID = "openai/o4-mini-fast"
	GatewayLanguageModelPerplexitySonar                  GatewayLanguageModelID = "perplexity/sonar"
	GatewayLanguageModelPerplexitySonarPro               GatewayLanguageModelID = "perplexity/sonar-pro"
	GatewayLanguageModelPerplexitySonarReasoningPro      GatewayLanguageModelID = "perplexity/sonar-reasoning-pro"
	GatewayLanguageModelPoolsideLagunaS21                GatewayLanguageModelID = "poolside/laguna-s-2.1"
	GatewayLanguageModelPoolsideLagunaS21Free            GatewayLanguageModelID = "poolside/laguna-s-2.1-free"
	GatewayLanguageModelQuiveraiArrow2                   GatewayLanguageModelID = "quiverai/arrow-2"
	GatewayLanguageModelQuiveraiArrow2Telos              GatewayLanguageModelID = "quiverai/arrow-2-telos"
	GatewayLanguageModelSakanaFuguMax                    GatewayLanguageModelID = "sakana/fugu-max"
	GatewayLanguageModelSakanaFuguUltra                  GatewayLanguageModelID = "sakana/fugu-ultra"
	GatewayLanguageModelSakanaFuguUltraV2                GatewayLanguageModelID = "sakana/fugu-ultra-v2"
	GatewayLanguageModelSakanaNamazu                     GatewayLanguageModelID = "sakana/namazu"
	GatewayLanguageModelSpacexaiGrok41FastNonReasoning   GatewayLanguageModelID = "spacexai/grok-4.1-fast-non-reasoning"
	GatewayLanguageModelSpacexaiGrok41FastReasoning      GatewayLanguageModelID = "spacexai/grok-4.1-fast-reasoning"
	GatewayLanguageModelSpacexaiGrok420MultiAgent        GatewayLanguageModelID = "spacexai/grok-4.20-multi-agent"
	GatewayLanguageModelSpacexaiGrok420MultiAgentBeta    GatewayLanguageModelID = "spacexai/grok-4.20-multi-agent-beta"
	GatewayLanguageModelSpacexaiGrok420NonReasoning      GatewayLanguageModelID = "spacexai/grok-4.20-non-reasoning"
	GatewayLanguageModelSpacexaiGrok420NonReasoningBeta  GatewayLanguageModelID = "spacexai/grok-4.20-non-reasoning-beta"
	GatewayLanguageModelSpacexaiGrok420Reasoning         GatewayLanguageModelID = "spacexai/grok-4.20-reasoning"
	GatewayLanguageModelSpacexaiGrok420ReasoningBeta     GatewayLanguageModelID = "spacexai/grok-4.20-reasoning-beta"
	GatewayLanguageModelSpacexaiGrok43                   GatewayLanguageModelID = "spacexai/grok-4.3"
	GatewayLanguageModelSpacexaiGrok45                   GatewayLanguageModelID = "spacexai/grok-4.5"
	GatewayLanguageModelSpacexaiGrok46                   GatewayLanguageModelID = "spacexai/grok-4.6"
	GatewayLanguageModelSpacexaiGrok47                   GatewayLanguageModelID = "spacexai/grok-4.7"
	GatewayLanguageModelSpacexaiGrokBuild01              GatewayLanguageModelID = "spacexai/grok-build-0.1"
	GatewayLanguageModelStepfunStep35Flash               GatewayLanguageModelID = "stepfun/step-3.5-flash"
	GatewayLanguageModelStepfunStep37Flash               GatewayLanguageModelID = "stepfun/step-3.7-flash"
	GatewayLanguageModelStepfunStep5Preview              GatewayLanguageModelID = "stepfun/step-5-preview"
	GatewayLanguageModelTencentHyMt2Lite                 GatewayLanguageModelID = "tencent/hy-mt2-lite"
	GatewayLanguageModelTencentHyMt2Plus                 GatewayLanguageModelID = "tencent/hy-mt2-plus"
	GatewayLanguageModelTencentHyMt2Pro                  GatewayLanguageModelID = "tencent/hy-mt2-pro"
	GatewayLanguageModelTencentHy3                       GatewayLanguageModelID = "tencent/hy3"
	GatewayLanguageModelTencentHy4Preview                GatewayLanguageModelID = "tencent/hy4-preview"
	GatewayLanguageModelThinkingmachinesInkling          GatewayLanguageModelID = "thinkingmachines/inkling"
	GatewayLanguageModelThinkingmachinesInklingSmall     GatewayLanguageModelID = "thinkingmachines/inkling-small"
	GatewayLanguageModelXiaomiMimoV25                    GatewayLanguageModelID = "xiaomi/mimo-v2.5"
	GatewayLanguageModelXiaomiMimoV25Pro                 GatewayLanguageModelID = "xiaomi/mimo-v2.5-pro"
	GatewayLanguageModelXiaomiMimoV26Flash               GatewayLanguageModelID = "xiaomi/mimo-v2.6-flash"
	GatewayLanguageModelXiaomiMimoV26Pro                 GatewayLanguageModelID = "xiaomi/mimo-v2.6-pro"
	GatewayLanguageModelXiaomiMimoV26ProUltraspeed       GatewayLanguageModelID = "xiaomi/mimo-v2.6-pro-ultraspeed"
	GatewayLanguageModelZaiGlm45                         GatewayLanguageModelID = "zai/glm-4.5"
	GatewayLanguageModelZaiGlm45Air                      GatewayLanguageModelID = "zai/glm-4.5-air"
	GatewayLanguageModelZaiGlm45v                        GatewayLanguageModelID = "zai/glm-4.5v"
	GatewayLanguageModelZaiGlm46                         GatewayLanguageModelID = "zai/glm-4.6"
	GatewayLanguageModelZaiGlm47                         GatewayLanguageModelID = "zai/glm-4.7"
	GatewayLanguageModelZaiGlm47Flash                    GatewayLanguageModelID = "zai/glm-4.7-flash"
	GatewayLanguageModelZaiGlm47Flashx                   GatewayLanguageModelID = "zai/glm-4.7-flashx"
	GatewayLanguageModelZaiGlm5                          GatewayLanguageModelID = "zai/glm-5"
	GatewayLanguageModelZaiGlm5Turbo                     GatewayLanguageModelID = "zai/glm-5-turbo"
	GatewayLanguageModelZaiGlm51                         GatewayLanguageModelID = "zai/glm-5.1"
	GatewayLanguageModelZaiGlm52                         GatewayLanguageModelID = "zai/glm-5.2"
	GatewayLanguageModelZaiGlm52Fast                     GatewayLanguageModelID = "zai/glm-5.2-fast"
	GatewayLanguageModelZaiGlm53                         GatewayLanguageModelID = "zai/glm-5.3"
	GatewayLanguageModelZaiGlm53Fast                     GatewayLanguageModelID = "zai/glm-5.3-fast"
	GatewayLanguageModelZaiGlm53Flash                    GatewayLanguageModelID = "zai/glm-5.3-flash"
	GatewayLanguageModelZaiGlm53Flashx                   GatewayLanguageModelID = "zai/glm-5.3-flashx"
	GatewayLanguageModelZaiGlm5vTurbo                    GatewayLanguageModelID = "zai/glm-5v-turbo"
)

// GatewayEmbeddingModelID constants mirror gateway-embedding-model-settings.ts.
const (
	GatewayEmbeddingModelAlibabaQwen3Embedding06b           GatewayEmbeddingModelID = "alibaba/qwen3-embedding-0.6b"
	GatewayEmbeddingModelAlibabaQwen3Embedding4b            GatewayEmbeddingModelID = "alibaba/qwen3-embedding-4b"
	GatewayEmbeddingModelAlibabaQwen3Embedding8b            GatewayEmbeddingModelID = "alibaba/qwen3-embedding-8b"
	GatewayEmbeddingModelAmazonTitanEmbedTextV2             GatewayEmbeddingModelID = "amazon/titan-embed-text-v2"
	GatewayEmbeddingModelCohereEmbedV40                     GatewayEmbeddingModelID = "cohere/embed-v4.0"
	GatewayEmbeddingModelGoogleGeminiEmbedding001           GatewayEmbeddingModelID = "google/gemini-embedding-001"
	GatewayEmbeddingModelGoogleGeminiEmbedding2             GatewayEmbeddingModelID = "google/gemini-embedding-2"
	GatewayEmbeddingModelGoogleTextEmbedding005             GatewayEmbeddingModelID = "google/text-embedding-005"
	GatewayEmbeddingModelGoogleTextMultilingualEmbedding002 GatewayEmbeddingModelID = "google/text-multilingual-embedding-002"
	GatewayEmbeddingModelMistralCodestralEmbed              GatewayEmbeddingModelID = "mistral/codestral-embed"
	GatewayEmbeddingModelMistralMistralEmbed                GatewayEmbeddingModelID = "mistral/mistral-embed"
	GatewayEmbeddingModelOpenaiTextEmbedding3Large          GatewayEmbeddingModelID = "openai/text-embedding-3-large"
	GatewayEmbeddingModelOpenaiTextEmbedding3Small          GatewayEmbeddingModelID = "openai/text-embedding-3-small"
	GatewayEmbeddingModelOpenaiTextEmbeddingAda002          GatewayEmbeddingModelID = "openai/text-embedding-ada-002"
	GatewayEmbeddingModelPerplexityPplxEmbedV106b           GatewayEmbeddingModelID = "perplexity/pplx-embed-v1-0.6b"
	GatewayEmbeddingModelPerplexityPplxEmbedV14b            GatewayEmbeddingModelID = "perplexity/pplx-embed-v1-4b"
	GatewayEmbeddingModelVoyageVoyage3Large                 GatewayEmbeddingModelID = "voyage/voyage-3-large"
	GatewayEmbeddingModelVoyageVoyage35                     GatewayEmbeddingModelID = "voyage/voyage-3.5"
	GatewayEmbeddingModelVoyageVoyage35Lite                 GatewayEmbeddingModelID = "voyage/voyage-3.5-lite"
	GatewayEmbeddingModelVoyageVoyage4                      GatewayEmbeddingModelID = "voyage/voyage-4"
	GatewayEmbeddingModelVoyageVoyage4Large                 GatewayEmbeddingModelID = "voyage/voyage-4-large"
	GatewayEmbeddingModelVoyageVoyage4Lite                  GatewayEmbeddingModelID = "voyage/voyage-4-lite"
	GatewayEmbeddingModelVoyageVoyageCode2                  GatewayEmbeddingModelID = "voyage/voyage-code-2"
	GatewayEmbeddingModelVoyageVoyageCode3                  GatewayEmbeddingModelID = "voyage/voyage-code-3"
	GatewayEmbeddingModelVoyageVoyageFinance2               GatewayEmbeddingModelID = "voyage/voyage-finance-2"
	GatewayEmbeddingModelVoyageVoyageLaw2                   GatewayEmbeddingModelID = "voyage/voyage-law-2"
)

// GatewayImageModelID constants mirror gateway-image-model-settings.ts.
const (
	GatewayImageModelBflFlux2Flex                GatewayImageModelID = "bfl/flux-2-flex"
	GatewayImageModelBflFlux2Klein4b             GatewayImageModelID = "bfl/flux-2-klein-4b"
	GatewayImageModelBflFlux2Klein9b             GatewayImageModelID = "bfl/flux-2-klein-9b"
	GatewayImageModelBflFlux2Max                 GatewayImageModelID = "bfl/flux-2-max"
	GatewayImageModelBflFlux2Pro                 GatewayImageModelID = "bfl/flux-2-pro"
	GatewayImageModelBflFluxKontextMax           GatewayImageModelID = "bfl/flux-kontext-max"
	GatewayImageModelBflFluxKontextPro           GatewayImageModelID = "bfl/flux-kontext-pro"
	GatewayImageModelBflFluxPro10Fill            GatewayImageModelID = "bfl/flux-pro-1.0-fill"
	GatewayImageModelBflFluxPro11                GatewayImageModelID = "bfl/flux-pro-1.1"
	GatewayImageModelBflFluxPro11Ultra           GatewayImageModelID = "bfl/flux-pro-1.1-ultra"
	GatewayImageModelBytedanceSeedream40         GatewayImageModelID = "bytedance/seedream-4.0"
	GatewayImageModelBytedanceSeedream45         GatewayImageModelID = "bytedance/seedream-4.5"
	GatewayImageModelBytedanceSeedream50Lite     GatewayImageModelID = "bytedance/seedream-5.0-lite"
	GatewayImageModelBytedanceSeedream50Pro      GatewayImageModelID = "bytedance/seedream-5.0-pro"
	GatewayImageModelMetaMuseImage10             GatewayImageModelID = "meta/muse-image-1.0"
	GatewayImageModelOpenaiGptImage1             GatewayImageModelID = "openai/gpt-image-1"
	GatewayImageModelOpenaiGptImage1Mini         GatewayImageModelID = "openai/gpt-image-1-mini"
	GatewayImageModelOpenaiGptImage15            GatewayImageModelID = "openai/gpt-image-1.5"
	GatewayImageModelOpenaiGptImage2             GatewayImageModelID = "openai/gpt-image-2"
	GatewayImageModelOpenaiGptImage25Flare       GatewayImageModelID = "openai/gpt-image-2.5-flare"
	GatewayImageModelOpenaiGptImage25Sunburst    GatewayImageModelID = "openai/gpt-image-2.5-sunburst"
	GatewayImageModelProdiaFluxFastSchnell       GatewayImageModelID = "prodia/flux-fast-schnell"
	GatewayImageModelQuiveraiArrow11             GatewayImageModelID = "quiverai/arrow-1.1"
	GatewayImageModelRecraftRecraftV2            GatewayImageModelID = "recraft/recraft-v2"
	GatewayImageModelRecraftRecraftV3            GatewayImageModelID = "recraft/recraft-v3"
	GatewayImageModelRecraftRecraftV4            GatewayImageModelID = "recraft/recraft-v4"
	GatewayImageModelRecraftRecraftV4Pro         GatewayImageModelID = "recraft/recraft-v4-pro"
	GatewayImageModelRecraftRecraftV41           GatewayImageModelID = "recraft/recraft-v4.1"
	GatewayImageModelRecraftRecraftV41Pro        GatewayImageModelID = "recraft/recraft-v4.1-pro"
	GatewayImageModelRecraftRecraftV41Utility    GatewayImageModelID = "recraft/recraft-v4.1-utility"
	GatewayImageModelRecraftRecraftV41UtilityPro GatewayImageModelID = "recraft/recraft-v4.1-utility-pro"
	GatewayImageModelSpacexaiGrokImagineImage    GatewayImageModelID = "spacexai/grok-imagine-image"
	GatewayImageModelSpacexaiGrokImagineImage20  GatewayImageModelID = "spacexai/grok-imagine-image-2.0"
)

// GatewayVideoModelID constants mirror gateway-video-model-settings.ts.
const (
	GatewayVideoModelAlibabaWanV25T2vPreview      GatewayVideoModelID = "alibaba/wan-v2.5-t2v-preview"
	GatewayVideoModelAlibabaWanV26I2v             GatewayVideoModelID = "alibaba/wan-v2.6-i2v"
	GatewayVideoModelAlibabaWanV26I2vFlash        GatewayVideoModelID = "alibaba/wan-v2.6-i2v-flash"
	GatewayVideoModelAlibabaWanV26R2v             GatewayVideoModelID = "alibaba/wan-v2.6-r2v"
	GatewayVideoModelAlibabaWanV26R2vFlash        GatewayVideoModelID = "alibaba/wan-v2.6-r2v-flash"
	GatewayVideoModelAlibabaWanV26T2v             GatewayVideoModelID = "alibaba/wan-v2.6-t2v"
	GatewayVideoModelAlibabaWanV27R2v             GatewayVideoModelID = "alibaba/wan-v2.7-r2v"
	GatewayVideoModelAlibabaWanV27T2v             GatewayVideoModelID = "alibaba/wan-v2.7-t2v"
	GatewayVideoModelAlibabaWanV30Video           GatewayVideoModelID = "alibaba/wan-v3.0-video"
	GatewayVideoModelAlibabaWanV30VideoPrime      GatewayVideoModelID = "alibaba/wan-v3.0-video-prime"
	GatewayVideoModelBflFlux3Video                GatewayVideoModelID = "bfl/flux-3-video"
	GatewayVideoModelBytedanceSeedance20          GatewayVideoModelID = "bytedance/seedance-2.0"
	GatewayVideoModelBytedanceSeedance20Fast      GatewayVideoModelID = "bytedance/seedance-2.0-fast"
	GatewayVideoModelBytedanceSeedance20Mini      GatewayVideoModelID = "bytedance/seedance-2.0-mini"
	GatewayVideoModelBytedanceSeedance25          GatewayVideoModelID = "bytedance/seedance-2.5"
	GatewayVideoModelBytedanceSeedanceV10Pro      GatewayVideoModelID = "bytedance/seedance-v1.0-pro"
	GatewayVideoModelBytedanceSeedanceV10ProFast  GatewayVideoModelID = "bytedance/seedance-v1.0-pro-fast"
	GatewayVideoModelBytedanceSeedanceV15Pro      GatewayVideoModelID = "bytedance/seedance-v1.5-pro"
	GatewayVideoModelGoogleVeo30FastGenerate001   GatewayVideoModelID = "google/veo-3.0-fast-generate-001"
	GatewayVideoModelGoogleVeo30Generate001       GatewayVideoModelID = "google/veo-3.0-generate-001"
	GatewayVideoModelGoogleVeo31FastGenerate001   GatewayVideoModelID = "google/veo-3.1-fast-generate-001"
	GatewayVideoModelGoogleVeo31Generate001       GatewayVideoModelID = "google/veo-3.1-generate-001"
	GatewayVideoModelGoogleVeo31LiteGenerate001   GatewayVideoModelID = "google/veo-3.1-lite-generate-001"
	GatewayVideoModelKlingaiKlingV25TurboI2v      GatewayVideoModelID = "klingai/kling-v2.5-turbo-i2v"
	GatewayVideoModelKlingaiKlingV25TurboT2v      GatewayVideoModelID = "klingai/kling-v2.5-turbo-t2v"
	GatewayVideoModelKlingaiKlingV26I2v           GatewayVideoModelID = "klingai/kling-v2.6-i2v"
	GatewayVideoModelKlingaiKlingV26MotionControl GatewayVideoModelID = "klingai/kling-v2.6-motion-control"
	GatewayVideoModelKlingaiKlingV26T2v           GatewayVideoModelID = "klingai/kling-v2.6-t2v"
	GatewayVideoModelKlingaiKlingV30I2v           GatewayVideoModelID = "klingai/kling-v3.0-i2v"
	GatewayVideoModelKlingaiKlingV30MotionControl GatewayVideoModelID = "klingai/kling-v3.0-motion-control"
	GatewayVideoModelKlingaiKlingV30T2v           GatewayVideoModelID = "klingai/kling-v3.0-t2v"
	GatewayVideoModelMinimaxMinimaxH3             GatewayVideoModelID = "minimax/minimax-h3"
	GatewayVideoModelMinimaxMinimaxH3Max          GatewayVideoModelID = "minimax/minimax-h3-max"
	GatewayVideoModelSpacexaiGrokImagineVideo     GatewayVideoModelID = "spacexai/grok-imagine-video"
	GatewayVideoModelSpacexaiGrokImagineVideo15   GatewayVideoModelID = "spacexai/grok-imagine-video-1.5"
)

// GatewayRerankingModelID constants mirror gateway-reranking-model-settings.ts.
const (
	GatewayRerankingModelCohereRerankV35    GatewayRerankingModelID = "cohere/rerank-v3.5"
	GatewayRerankingModelCohereRerankV4Fast GatewayRerankingModelID = "cohere/rerank-v4-fast"
	GatewayRerankingModelCohereRerankV4Pro  GatewayRerankingModelID = "cohere/rerank-v4-pro"
	GatewayRerankingModelVoyageRerank25     GatewayRerankingModelID = "voyage/rerank-2.5"
	GatewayRerankingModelVoyageRerank25Lite GatewayRerankingModelID = "voyage/rerank-2.5-lite"
)

// GatewaySpeechModelID constants mirror gateway-speech-model-settings.ts.
const (
	GatewaySpeechModelFishAudioS1                GatewaySpeechModelID = "fish-audio/s1"
	GatewaySpeechModelFishAudioS2Pro             GatewaySpeechModelID = "fish-audio/s2-pro"
	GatewaySpeechModelFishAudioS21Pro            GatewaySpeechModelID = "fish-audio/s2.1-pro"
	GatewaySpeechModelGoogleGemini38FlashTts     GatewaySpeechModelID = "google/gemini-3.8-flash-tts"
	GatewaySpeechModelGoogleGemini38FlashLiteTts GatewaySpeechModelID = "google/gemini-3.8-flash-lite-tts"
	GatewaySpeechModelOpenaiTts1                 GatewaySpeechModelID = "openai/tts-1"
	GatewaySpeechModelOpenaiTts1Hd               GatewaySpeechModelID = "openai/tts-1-hd"
	GatewaySpeechModelSpacexaiGrokTts            GatewaySpeechModelID = "spacexai/grok-tts"
)

// GatewayTranscriptionModelID constants mirror gateway-transcription-model-settings.ts.
const (
	GatewayTranscriptionModelFishAudioTranscribe1         GatewayTranscriptionModelID = "fish-audio/transcribe-1"
	GatewayTranscriptionModelGoogleGemini35Transcribe     GatewayTranscriptionModelID = "google/gemini-3.5-transcribe"
	GatewayTranscriptionModelGoogleGemini35TranscribeLive GatewayTranscriptionModelID = "google/gemini-3.5-transcribe-live"
	GatewayTranscriptionModelOpenaiGpt4oMiniTranscribe    GatewayTranscriptionModelID = "openai/gpt-4o-mini-transcribe"
	GatewayTranscriptionModelOpenaiGpt4oTranscribe        GatewayTranscriptionModelID = "openai/gpt-4o-transcribe"
	GatewayTranscriptionModelOpenaiGptRealtimeWhisper     GatewayTranscriptionModelID = "openai/gpt-realtime-whisper"
	GatewayTranscriptionModelOpenaiWhisper1               GatewayTranscriptionModelID = "openai/whisper-1"
	GatewayTranscriptionModelSpacexaiGrokStt              GatewayTranscriptionModelID = "spacexai/grok-stt"
)

// GatewayRealtimeModelID constants mirror gateway-realtime-model-settings.ts.
const (
	GatewayRealtimeModelGoogleGemini38Live                 GatewayRealtimeModelID = "google/gemini-3.8-live"
	GatewayRealtimeModelGoogleGemini38LiveExtendedThinking GatewayRealtimeModelID = "google/gemini-3.8-live-extended-thinking"
	GatewayRealtimeModelOpenaiGptLive1                     GatewayRealtimeModelID = "openai/gpt-live-1"
	GatewayRealtimeModelOpenaiGptRealtime15                GatewayRealtimeModelID = "openai/gpt-realtime-1.5"
	GatewayRealtimeModelOpenaiGptRealtime2                 GatewayRealtimeModelID = "openai/gpt-realtime-2"
	GatewayRealtimeModelOpenaiGptRealtime21                GatewayRealtimeModelID = "openai/gpt-realtime-2.1"
	GatewayRealtimeModelOpenaiGptRealtimeMini              GatewayRealtimeModelID = "openai/gpt-realtime-mini"
	GatewayRealtimeModelSpacexaiGrokVoiceThinkFast10       GatewayRealtimeModelID = "spacexai/grok-voice-think-fast-1.0"
	GatewayRealtimeModelSpacexaiGrokVoiceThinkFast20       GatewayRealtimeModelID = "spacexai/grok-voice-think-fast-2.0"
)

// GatewayEvaluationModelID constants mirror gateway-evaluation-model-settings.ts.
const (
	GatewayEvaluationModelTypesafeAiJev GatewayEvaluationModelID = "typesafe-ai/jev"
)

// GatewayLanguageModelIDs lists the suggested gateway language model IDs from gateway-language-model-settings.ts.
var GatewayLanguageModelIDs = []GatewayLanguageModelID{
	GatewayLanguageModelAlibabaQwen314b,
	GatewayLanguageModelAlibabaQwen3235b,
	GatewayLanguageModelAlibabaQwen330b,
	GatewayLanguageModelAlibabaQwen332b,
	GatewayLanguageModelAlibabaQwen36MaxPreview,
	GatewayLanguageModelAlibabaQwen3235bA22bThinking,
	GatewayLanguageModelAlibabaQwen3Coder,
	GatewayLanguageModelAlibabaQwen3Coder30bA3b,
	GatewayLanguageModelAlibabaQwen3CoderNext,
	GatewayLanguageModelAlibabaQwen3CoderPlus,
	GatewayLanguageModelAlibabaQwen3Max,
	GatewayLanguageModelAlibabaQwen3MaxPreview,
	GatewayLanguageModelAlibabaQwen3MaxThinking,
	GatewayLanguageModelAlibabaQwen3Next80bA3bInstruct,
	GatewayLanguageModelAlibabaQwen3Next80bA3bThinking,
	GatewayLanguageModelAlibabaQwen3Vl235bA22bInstruct,
	GatewayLanguageModelAlibabaQwen3VlInstruct,
	GatewayLanguageModelAlibabaQwen3VlThinking,
	GatewayLanguageModelAlibabaQwen35Flash,
	GatewayLanguageModelAlibabaQwen35Plus,
	GatewayLanguageModelAlibabaQwen3627b,
	GatewayLanguageModelAlibabaQwen36Plus,
	GatewayLanguageModelAlibabaQwen37Flash,
	GatewayLanguageModelAlibabaQwen37Max,
	GatewayLanguageModelAlibabaQwen37Plus,
	GatewayLanguageModelAlibabaQwen3824tA95b,
	GatewayLanguageModelAlibabaQwen3827b,
	GatewayLanguageModelAlibabaQwen38Flash,
	GatewayLanguageModelAlibabaQwen38Max,
	GatewayLanguageModelAlibabaQwen38Max0902,
	GatewayLanguageModelAlibabaQwen38OmniFlash,
	GatewayLanguageModelAmazonNova2Lite,
	GatewayLanguageModelAmazonNovaLite,
	GatewayLanguageModelAmazonNovaMicro,
	GatewayLanguageModelAmazonNovaPro,
	GatewayLanguageModelAnthropicClaude3Haiku,
	GatewayLanguageModelAnthropicClaudeFable5,
	GatewayLanguageModelAnthropicClaudeFable51,
	GatewayLanguageModelAnthropicClaudeHaiku45,
	GatewayLanguageModelAnthropicClaudeOpus4,
	GatewayLanguageModelAnthropicClaudeOpus45,
	GatewayLanguageModelAnthropicClaudeOpus46,
	GatewayLanguageModelAnthropicClaudeOpus47,
	GatewayLanguageModelAnthropicClaudeOpus48,
	GatewayLanguageModelAnthropicClaudeOpus48Fast,
	GatewayLanguageModelAnthropicClaudeOpus5,
	GatewayLanguageModelAnthropicClaudeOpus5Fast,
	GatewayLanguageModelAnthropicClaudeOpus55,
	GatewayLanguageModelAnthropicClaudeSonnet4,
	GatewayLanguageModelAnthropicClaudeSonnet45,
	GatewayLanguageModelAnthropicClaudeSonnet46,
	GatewayLanguageModelAnthropicClaudeSonnet5,
	GatewayLanguageModelAnthropicClaudeSonnet55,
	GatewayLanguageModelArceeAiTrinityLargeThinking,
	GatewayLanguageModelBytedanceSeed16,
	GatewayLanguageModelBytedanceSeed18,
	GatewayLanguageModelBytedanceSeed21Turbo,
	GatewayLanguageModelCohereCommandA,
	GatewayLanguageModelDeepseekDeepseekR1,
	GatewayLanguageModelDeepseekDeepseekV31,
	GatewayLanguageModelDeepseekDeepseekV31Terminus,
	GatewayLanguageModelDeepseekDeepseekV32,
	GatewayLanguageModelDeepseekDeepseekV32Thinking,
	GatewayLanguageModelDeepseekDeepseekV4Flash,
	GatewayLanguageModelDeepseekDeepseekV4Flash0731,
	GatewayLanguageModelDeepseekDeepseekV4FlashVisionExp,
	GatewayLanguageModelDeepseekDeepseekV4Pro,
	GatewayLanguageModelDeepseekDeepseekV4Pro0813,
	GatewayLanguageModelDeepseekDeepseekV41Flash,
	GatewayLanguageModelGoogleGemini25Flash,
	GatewayLanguageModelGoogleGemini25FlashImage,
	GatewayLanguageModelGoogleGemini25FlashLite,
	GatewayLanguageModelGoogleGemini25Pro,
	GatewayLanguageModelGoogleGemini3Flash,
	GatewayLanguageModelGoogleGemini3ProImage,
	GatewayLanguageModelGoogleGemini31FlashImage,
	GatewayLanguageModelGoogleGemini31FlashImagePreview,
	GatewayLanguageModelGoogleGemini31FlashLite,
	GatewayLanguageModelGoogleGemini31FlashLiteImage,
	GatewayLanguageModelGoogleGemini31ProPreview,
	GatewayLanguageModelGoogleGemini35Flash,
	GatewayLanguageModelGoogleGemini35FlashLite,
	GatewayLanguageModelGoogleGemini36Flash,
	GatewayLanguageModelGoogleGemini37Flash,
	GatewayLanguageModelGoogleGemini38Flash,
	GatewayLanguageModelGoogleGeminiOmniFlashPreview,
	GatewayLanguageModelGoogleGemma426bA4bIt,
	GatewayLanguageModelGoogleGemma431bIt,
	GatewayLanguageModelInceptionMercury2,
	GatewayLanguageModelInceptionMercury25,
	GatewayLanguageModelInceptionMercuryCoderSmall,
	GatewayLanguageModelInclusionaiLing30Flash,
	GatewayLanguageModelInclusionaiLing30FlashFin,
	GatewayLanguageModelInclusionaiLing30FlashFinFree,
	GatewayLanguageModelInclusionaiLing30FlashSante,
	GatewayLanguageModelInclusionaiLing30FlashSanteFree,
	GatewayLanguageModelInclusionaiLing30FlashVl,
	GatewayLanguageModelInclusionaiLing30FlashVlFree,
	GatewayLanguageModelInferenceNetSchematronV2Small,
	GatewayLanguageModelInferenceNetSchematronV2Turbo,
	GatewayLanguageModelInterfazeInterfazeBeta,
	GatewayLanguageModelMetaLlama3170b,
	GatewayLanguageModelMetaLlama318b,
	GatewayLanguageModelMetaLlama3370b,
	GatewayLanguageModelMetaLlama4Maverick,
	GatewayLanguageModelMetaLlama4Scout,
	GatewayLanguageModelMetaMuseGlimmer30b,
	GatewayLanguageModelMetaMuseSpark11,
	GatewayLanguageModelMetaMuseSpark12,
	GatewayLanguageModelMetaMuseSpark12Contributor,
	GatewayLanguageModelMetaMuseSpark13,
	GatewayLanguageModelMetaMuseSpark13Contributor,
	GatewayLanguageModelMinimaxMinimaxM2,
	GatewayLanguageModelMinimaxMinimaxM21,
	GatewayLanguageModelMinimaxMinimaxM21Lightning,
	GatewayLanguageModelMinimaxMinimaxM25,
	GatewayLanguageModelMinimaxMinimaxM25Highspeed,
	GatewayLanguageModelMinimaxMinimaxM27,
	GatewayLanguageModelMinimaxMinimaxM27Highspeed,
	GatewayLanguageModelMinimaxMinimaxM3,
	GatewayLanguageModelMistralCodestral,
	GatewayLanguageModelMistralMinistral14b,
	GatewayLanguageModelMistralMinistral3b,
	GatewayLanguageModelMistralMinistral8b,
	GatewayLanguageModelMistralMistralLarge3,
	GatewayLanguageModelMistralMistralMedium35,
	GatewayLanguageModelMistralMistralNemo,
	GatewayLanguageModelMistralMistralSmall,
	GatewayLanguageModelMixedbreadToast1,
	GatewayLanguageModelMoonshotaiKimiK2,
	GatewayLanguageModelMoonshotaiKimiK2Thinking,
	GatewayLanguageModelMoonshotaiKimiK25,
	GatewayLanguageModelMoonshotaiKimiK26,
	GatewayLanguageModelMoonshotaiKimiK27Code,
	GatewayLanguageModelMoonshotaiKimiK27CodeHighspeed,
	GatewayLanguageModelMoonshotaiKimiK3,
	GatewayLanguageModelMoonshotaiKimiK3Fast,
	GatewayLanguageModelMorphMorphV3Fast,
	GatewayLanguageModelMorphMorphV3Large,
	GatewayLanguageModelNvidiaNemotron3Nano30bA3b,
	GatewayLanguageModelNvidiaNemotron3Super120bA12b,
	GatewayLanguageModelNvidiaNemotron3Ultra550bA55b,
	GatewayLanguageModelNvidiaNemotron35Lightning,
	GatewayLanguageModelNvidiaNemotronNano12bV2Vl,
	GatewayLanguageModelNvidiaNemotronNano9bV2,
	GatewayLanguageModelOpenaiGpt35Turbo,
	GatewayLanguageModelOpenaiGpt4Turbo,
	GatewayLanguageModelOpenaiGpt41,
	GatewayLanguageModelOpenaiGpt41Fast,
	GatewayLanguageModelOpenaiGpt41Mini,
	GatewayLanguageModelOpenaiGpt41MiniFast,
	GatewayLanguageModelOpenaiGpt41Nano,
	GatewayLanguageModelOpenaiGpt41NanoFast,
	GatewayLanguageModelOpenaiGpt4o,
	GatewayLanguageModelOpenaiGpt4oFast,
	GatewayLanguageModelOpenaiGpt4oMini,
	GatewayLanguageModelOpenaiGpt4oMiniFast,
	GatewayLanguageModelOpenaiGpt5,
	GatewayLanguageModelOpenaiGpt5Codex,
	GatewayLanguageModelOpenaiGpt5Fast,
	GatewayLanguageModelOpenaiGpt5Mini,
	GatewayLanguageModelOpenaiGpt5MiniFast,
	GatewayLanguageModelOpenaiGpt5Nano,
	GatewayLanguageModelOpenaiGpt5Pro,
	GatewayLanguageModelOpenaiGpt51Codex,
	GatewayLanguageModelOpenaiGpt51CodexMax,
	GatewayLanguageModelOpenaiGpt51CodexMini,
	GatewayLanguageModelOpenaiGpt51Thinking,
	GatewayLanguageModelOpenaiGpt51ThinkingFast,
	GatewayLanguageModelOpenaiGpt52,
	GatewayLanguageModelOpenaiGpt52Codex,
	GatewayLanguageModelOpenaiGpt52Fast,
	GatewayLanguageModelOpenaiGpt52Pro,
	GatewayLanguageModelOpenaiGpt53Codex,
	GatewayLanguageModelOpenaiGpt53CodexFast,
	GatewayLanguageModelOpenaiGpt54,
	GatewayLanguageModelOpenaiGpt54Fast,
	GatewayLanguageModelOpenaiGpt54Mini,
	GatewayLanguageModelOpenaiGpt54MiniFast,
	GatewayLanguageModelOpenaiGpt54Nano,
	GatewayLanguageModelOpenaiGpt54Pro,
	GatewayLanguageModelOpenaiGpt55,
	GatewayLanguageModelOpenaiGpt55Fast,
	GatewayLanguageModelOpenaiGpt55Pro,
	GatewayLanguageModelOpenaiGpt56Luna,
	GatewayLanguageModelOpenaiGpt56LunaFast,
	GatewayLanguageModelOpenaiGpt56Sol,
	GatewayLanguageModelOpenaiGpt56SolFast,
	GatewayLanguageModelOpenaiGpt56Terra,
	GatewayLanguageModelOpenaiGpt56TerraFast,
	GatewayLanguageModelOpenaiGpt6Astra,
	GatewayLanguageModelOpenaiGpt6AstraFast,
	GatewayLanguageModelOpenaiGpt6Luna,
	GatewayLanguageModelOpenaiGpt6LunaFast,
	GatewayLanguageModelOpenaiGpt6Sol,
	GatewayLanguageModelOpenaiGpt6SolFast,
	GatewayLanguageModelOpenaiGptOss120b,
	GatewayLanguageModelOpenaiGptOss20b,
	GatewayLanguageModelOpenaiGptOssSafeguard120b,
	GatewayLanguageModelOpenaiGptOssSafeguard20b,
	GatewayLanguageModelOpenaiO1,
	GatewayLanguageModelOpenaiO3,
	GatewayLanguageModelOpenaiO3Fast,
	GatewayLanguageModelOpenaiO3Mini,
	GatewayLanguageModelOpenaiO3Pro,
	GatewayLanguageModelOpenaiO4Mini,
	GatewayLanguageModelOpenaiO4MiniFast,
	GatewayLanguageModelPerplexitySonar,
	GatewayLanguageModelPerplexitySonarPro,
	GatewayLanguageModelPerplexitySonarReasoningPro,
	GatewayLanguageModelPoolsideLagunaS21,
	GatewayLanguageModelPoolsideLagunaS21Free,
	GatewayLanguageModelQuiveraiArrow2,
	GatewayLanguageModelQuiveraiArrow2Telos,
	GatewayLanguageModelSakanaFuguMax,
	GatewayLanguageModelSakanaFuguUltra,
	GatewayLanguageModelSakanaFuguUltraV2,
	GatewayLanguageModelSakanaNamazu,
	GatewayLanguageModelSpacexaiGrok41FastNonReasoning,
	GatewayLanguageModelSpacexaiGrok41FastReasoning,
	GatewayLanguageModelSpacexaiGrok420MultiAgent,
	GatewayLanguageModelSpacexaiGrok420MultiAgentBeta,
	GatewayLanguageModelSpacexaiGrok420NonReasoning,
	GatewayLanguageModelSpacexaiGrok420NonReasoningBeta,
	GatewayLanguageModelSpacexaiGrok420Reasoning,
	GatewayLanguageModelSpacexaiGrok420ReasoningBeta,
	GatewayLanguageModelSpacexaiGrok43,
	GatewayLanguageModelSpacexaiGrok45,
	GatewayLanguageModelSpacexaiGrok46,
	GatewayLanguageModelSpacexaiGrok47,
	GatewayLanguageModelSpacexaiGrokBuild01,
	GatewayLanguageModelStepfunStep35Flash,
	GatewayLanguageModelStepfunStep37Flash,
	GatewayLanguageModelStepfunStep5Preview,
	GatewayLanguageModelTencentHyMt2Lite,
	GatewayLanguageModelTencentHyMt2Plus,
	GatewayLanguageModelTencentHyMt2Pro,
	GatewayLanguageModelTencentHy3,
	GatewayLanguageModelTencentHy4Preview,
	GatewayLanguageModelThinkingmachinesInkling,
	GatewayLanguageModelThinkingmachinesInklingSmall,
	GatewayLanguageModelXiaomiMimoV25,
	GatewayLanguageModelXiaomiMimoV25Pro,
	GatewayLanguageModelXiaomiMimoV26Flash,
	GatewayLanguageModelXiaomiMimoV26Pro,
	GatewayLanguageModelXiaomiMimoV26ProUltraspeed,
	GatewayLanguageModelZaiGlm45,
	GatewayLanguageModelZaiGlm45Air,
	GatewayLanguageModelZaiGlm45v,
	GatewayLanguageModelZaiGlm46,
	GatewayLanguageModelZaiGlm47,
	GatewayLanguageModelZaiGlm47Flash,
	GatewayLanguageModelZaiGlm47Flashx,
	GatewayLanguageModelZaiGlm5,
	GatewayLanguageModelZaiGlm5Turbo,
	GatewayLanguageModelZaiGlm51,
	GatewayLanguageModelZaiGlm52,
	GatewayLanguageModelZaiGlm52Fast,
	GatewayLanguageModelZaiGlm53,
	GatewayLanguageModelZaiGlm53Fast,
	GatewayLanguageModelZaiGlm53Flash,
	GatewayLanguageModelZaiGlm53Flashx,
	GatewayLanguageModelZaiGlm5vTurbo,
}

// GatewayEmbeddingModelIDs lists the suggested gateway embedding model IDs from gateway-embedding-model-settings.ts.
var GatewayEmbeddingModelIDs = []GatewayEmbeddingModelID{
	GatewayEmbeddingModelAlibabaQwen3Embedding06b,
	GatewayEmbeddingModelAlibabaQwen3Embedding4b,
	GatewayEmbeddingModelAlibabaQwen3Embedding8b,
	GatewayEmbeddingModelAmazonTitanEmbedTextV2,
	GatewayEmbeddingModelCohereEmbedV40,
	GatewayEmbeddingModelGoogleGeminiEmbedding001,
	GatewayEmbeddingModelGoogleGeminiEmbedding2,
	GatewayEmbeddingModelGoogleTextEmbedding005,
	GatewayEmbeddingModelGoogleTextMultilingualEmbedding002,
	GatewayEmbeddingModelMistralCodestralEmbed,
	GatewayEmbeddingModelMistralMistralEmbed,
	GatewayEmbeddingModelOpenaiTextEmbedding3Large,
	GatewayEmbeddingModelOpenaiTextEmbedding3Small,
	GatewayEmbeddingModelOpenaiTextEmbeddingAda002,
	GatewayEmbeddingModelPerplexityPplxEmbedV106b,
	GatewayEmbeddingModelPerplexityPplxEmbedV14b,
	GatewayEmbeddingModelVoyageVoyage3Large,
	GatewayEmbeddingModelVoyageVoyage35,
	GatewayEmbeddingModelVoyageVoyage35Lite,
	GatewayEmbeddingModelVoyageVoyage4,
	GatewayEmbeddingModelVoyageVoyage4Large,
	GatewayEmbeddingModelVoyageVoyage4Lite,
	GatewayEmbeddingModelVoyageVoyageCode2,
	GatewayEmbeddingModelVoyageVoyageCode3,
	GatewayEmbeddingModelVoyageVoyageFinance2,
	GatewayEmbeddingModelVoyageVoyageLaw2,
}

// GatewayImageModelIDs lists the suggested gateway image model IDs from gateway-image-model-settings.ts.
var GatewayImageModelIDs = []GatewayImageModelID{
	GatewayImageModelBflFlux2Flex,
	GatewayImageModelBflFlux2Klein4b,
	GatewayImageModelBflFlux2Klein9b,
	GatewayImageModelBflFlux2Max,
	GatewayImageModelBflFlux2Pro,
	GatewayImageModelBflFluxKontextMax,
	GatewayImageModelBflFluxKontextPro,
	GatewayImageModelBflFluxPro10Fill,
	GatewayImageModelBflFluxPro11,
	GatewayImageModelBflFluxPro11Ultra,
	GatewayImageModelBytedanceSeedream40,
	GatewayImageModelBytedanceSeedream45,
	GatewayImageModelBytedanceSeedream50Lite,
	GatewayImageModelBytedanceSeedream50Pro,
	GatewayImageModelMetaMuseImage10,
	GatewayImageModelOpenaiGptImage1,
	GatewayImageModelOpenaiGptImage1Mini,
	GatewayImageModelOpenaiGptImage15,
	GatewayImageModelOpenaiGptImage2,
	GatewayImageModelOpenaiGptImage25Flare,
	GatewayImageModelOpenaiGptImage25Sunburst,
	GatewayImageModelProdiaFluxFastSchnell,
	GatewayImageModelQuiveraiArrow11,
	GatewayImageModelRecraftRecraftV2,
	GatewayImageModelRecraftRecraftV3,
	GatewayImageModelRecraftRecraftV4,
	GatewayImageModelRecraftRecraftV4Pro,
	GatewayImageModelRecraftRecraftV41,
	GatewayImageModelRecraftRecraftV41Pro,
	GatewayImageModelRecraftRecraftV41Utility,
	GatewayImageModelRecraftRecraftV41UtilityPro,
	GatewayImageModelSpacexaiGrokImagineImage,
	GatewayImageModelSpacexaiGrokImagineImage20,
}

// GatewayVideoModelIDs lists the suggested gateway video model IDs from gateway-video-model-settings.ts.
var GatewayVideoModelIDs = []GatewayVideoModelID{
	GatewayVideoModelAlibabaWanV25T2vPreview,
	GatewayVideoModelAlibabaWanV26I2v,
	GatewayVideoModelAlibabaWanV26I2vFlash,
	GatewayVideoModelAlibabaWanV26R2v,
	GatewayVideoModelAlibabaWanV26R2vFlash,
	GatewayVideoModelAlibabaWanV26T2v,
	GatewayVideoModelAlibabaWanV27R2v,
	GatewayVideoModelAlibabaWanV27T2v,
	GatewayVideoModelAlibabaWanV30Video,
	GatewayVideoModelAlibabaWanV30VideoPrime,
	GatewayVideoModelBflFlux3Video,
	GatewayVideoModelBytedanceSeedance20,
	GatewayVideoModelBytedanceSeedance20Fast,
	GatewayVideoModelBytedanceSeedance20Mini,
	GatewayVideoModelBytedanceSeedance25,
	GatewayVideoModelBytedanceSeedanceV10Pro,
	GatewayVideoModelBytedanceSeedanceV10ProFast,
	GatewayVideoModelBytedanceSeedanceV15Pro,
	GatewayVideoModelGoogleVeo30FastGenerate001,
	GatewayVideoModelGoogleVeo30Generate001,
	GatewayVideoModelGoogleVeo31FastGenerate001,
	GatewayVideoModelGoogleVeo31Generate001,
	GatewayVideoModelGoogleVeo31LiteGenerate001,
	GatewayVideoModelKlingaiKlingV25TurboI2v,
	GatewayVideoModelKlingaiKlingV25TurboT2v,
	GatewayVideoModelKlingaiKlingV26I2v,
	GatewayVideoModelKlingaiKlingV26MotionControl,
	GatewayVideoModelKlingaiKlingV26T2v,
	GatewayVideoModelKlingaiKlingV30I2v,
	GatewayVideoModelKlingaiKlingV30MotionControl,
	GatewayVideoModelKlingaiKlingV30T2v,
	GatewayVideoModelMinimaxMinimaxH3,
	GatewayVideoModelMinimaxMinimaxH3Max,
	GatewayVideoModelSpacexaiGrokImagineVideo,
	GatewayVideoModelSpacexaiGrokImagineVideo15,
}

// GatewayRerankingModelIDs lists the suggested gateway reranking model IDs from gateway-reranking-model-settings.ts.
var GatewayRerankingModelIDs = []GatewayRerankingModelID{
	GatewayRerankingModelCohereRerankV35,
	GatewayRerankingModelCohereRerankV4Fast,
	GatewayRerankingModelCohereRerankV4Pro,
	GatewayRerankingModelVoyageRerank25,
	GatewayRerankingModelVoyageRerank25Lite,
}

// GatewaySpeechModelIDs lists the suggested gateway speech model IDs from gateway-speech-model-settings.ts.
var GatewaySpeechModelIDs = []GatewaySpeechModelID{
	GatewaySpeechModelFishAudioS1,
	GatewaySpeechModelFishAudioS2Pro,
	GatewaySpeechModelFishAudioS21Pro,
	GatewaySpeechModelGoogleGemini38FlashTts,
	GatewaySpeechModelGoogleGemini38FlashLiteTts,
	GatewaySpeechModelOpenaiTts1,
	GatewaySpeechModelOpenaiTts1Hd,
	GatewaySpeechModelSpacexaiGrokTts,
}

// GatewayTranscriptionModelIDs lists the suggested gateway transcription model IDs from gateway-transcription-model-settings.ts.
var GatewayTranscriptionModelIDs = []GatewayTranscriptionModelID{
	GatewayTranscriptionModelFishAudioTranscribe1,
	GatewayTranscriptionModelGoogleGemini35Transcribe,
	GatewayTranscriptionModelGoogleGemini35TranscribeLive,
	GatewayTranscriptionModelOpenaiGpt4oMiniTranscribe,
	GatewayTranscriptionModelOpenaiGpt4oTranscribe,
	GatewayTranscriptionModelOpenaiGptRealtimeWhisper,
	GatewayTranscriptionModelOpenaiWhisper1,
	GatewayTranscriptionModelSpacexaiGrokStt,
}

// GatewayRealtimeModelIDs lists the suggested gateway realtime model IDs from gateway-realtime-model-settings.ts.
var GatewayRealtimeModelIDs = []GatewayRealtimeModelID{
	GatewayRealtimeModelGoogleGemini38Live,
	GatewayRealtimeModelGoogleGemini38LiveExtendedThinking,
	GatewayRealtimeModelOpenaiGptLive1,
	GatewayRealtimeModelOpenaiGptRealtime15,
	GatewayRealtimeModelOpenaiGptRealtime2,
	GatewayRealtimeModelOpenaiGptRealtime21,
	GatewayRealtimeModelOpenaiGptRealtimeMini,
	GatewayRealtimeModelSpacexaiGrokVoiceThinkFast10,
	GatewayRealtimeModelSpacexaiGrokVoiceThinkFast20,
}

// GatewayEvaluationModelIDs lists the suggested gateway evaluation model IDs from gateway-evaluation-model-settings.ts.
var GatewayEvaluationModelIDs = []GatewayEvaluationModelID{
	GatewayEvaluationModelTypesafeAiJev,
}
