package main

import (
	"context"
	"fmt"
	"log"
	"os"

	"github.com/digitallysavvy/go-ai/pkg/provider"
	"github.com/digitallysavvy/go-ai/pkg/providers/xai"
)

func main() {
	// Get API key from environment
	apiKey := os.Getenv("XAI_API_KEY")
	if apiKey == "" {
		log.Fatal("XAI_API_KEY environment variable is required")
	}

	// Get source image URL from environment
	imageURL := os.Getenv("SOURCE_IMAGE_URL")
	if imageURL == "" {
		log.Fatal("SOURCE_IMAGE_URL environment variable is required")
	}

	// Create XAI provider
	prov := xai.New(xai.Config{
		APIKey: apiKey,
	})

	// Get image model
	model, err := prov.ImageModel("grok-image-1")
	if err != nil {
		log.Fatalf("Failed to get image model: %v", err)
	}

	ctx := context.Background()

	// Generate variations
	n := 4
	fmt.Println("Generating image variations...")
	fmt.Printf("Source Image: %s\n", imageURL)
	fmt.Printf("Number of variations: %d\n", n)
	fmt.Println("Prompt: Generate creative variations with different styles and compositions")

	result, err := model.DoGenerate(ctx, &provider.ImageGenerateOptions{
		Prompt: "Generate creative variations with different styles and compositions",
		N:      &n,
		Files: []provider.ImageFile{
			{
				Type: "url",
				URL:  imageURL,
			},
		},
	})

	if err != nil {
		log.Fatalf("Failed to generate variations: %v", err)
	}

	// Print results
	fmt.Println("\n✅ Image variations generated successfully!")
	fmt.Printf("Total variations generated: %d\n", result.Usage.ImageCount)
	fmt.Printf("Returned image size: %d bytes\n", len(result.Image))
	fmt.Printf("MIME type: %s\n", result.MimeType)

	// Note about Go limitation
	fmt.Println("\n📝 Note: Go's ImageResult currently only returns the first image.")
	fmt.Printf("However, %d images were generated by the API.\n", result.Usage.ImageCount)
	fmt.Println("The full set of images is available via the XAI API response.")

	// Save first variation
	outputFile := "variation-1.png"
	if err := os.WriteFile(outputFile, result.Image, 0644); err != nil {
		log.Fatalf("Failed to save image: %v", err)
	}

	fmt.Printf("\n💾 First variation saved to: %s\n", outputFile)

	fmt.Println("\n💡 Tip: For more variations, you can:")
	fmt.Println("  - Call the API multiple times with different seeds")
	fmt.Println("  - Modify the prompt for different styles")
}
