body:
  - type: markdown
    attributes:
      value: |
        # Go-AI Discussion
        Use this discussion to ask questions about using or contributing to Go-AI.
  - type: textarea
    attributes:
      label: Question
    validations:
      required: true
