body:
  - type: markdown
    attributes:
      value: |
        # Go-AI Show and Tell
        Share examples of what you built with Go-AI.
  - type: textarea
    attributes:
      label: Post
    validations:
      required: true
