blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/digitallysavvy/go-ai/discussions
    about: Please ask questions in this repository's Discussions forum.
