package ai

import "github.com/digitallysavvy/go-ai/pkg/provider/types"

// ObjectOnStartEvent is fired once when GenerateObject or StreamObject begins,
// before any LLM call is made. Passed to ExperimentalOnStart callbacks.
//
// Note on cancellation: the TypeScript SDK includes an abortSignal field on this
// event. In Go, the ctx parameter passed to the callback serves this role —
// pass ctx to any operations that should respect cancellation.
type ObjectOnStartEvent struct {
	// CallID uniquely identifies this generation call, used to correlate events.
	CallID string

	// OperationID identifies the operation (e.g. "ai.generateObject" or "ai.streamObject").
	OperationID string

	// Provider is the provider identifier (e.g., "openai", "anthropic").
	Provider string

	// ModelID is the specific model identifier (e.g., "gpt-4o").
	ModelID string

	// System is the system message provided to the model.
	System string

	// Prompt is the text prompt, if provided via the prompt option.
	Prompt string

	// Messages is the messages array, if provided via the messages option.
	Messages []types.Message

	// MaxOutputTokens is the maximum number of tokens to generate.
	MaxOutputTokens *int

	// Temperature is the sampling temperature.
	Temperature *float64

	// TopP is the top-p (nucleus) sampling parameter.
	TopP *float64

	// TopK is the top-k sampling parameter.
	TopK *int

	// PresencePenalty is the presence penalty.
	PresencePenalty *float64

	// FrequencyPenalty is the frequency penalty.
	FrequencyPenalty *float64

	// Seed is the random seed for reproducible generation.
	Seed *int

	// MaxRetries is the maximum number of retries for failed requests.
	MaxRetries int

	// Headers are additional HTTP headers sent with the request.
	Headers map[string]string

	// ProviderOptions are additional provider-specific options.
	ProviderOptions map[string]interface{}

	// Output is the output strategy type.
	Output ObjectOutputMode

	// Schema is the JSON Schema used for object generation, if any.
	Schema map[string]interface{}

	// SchemaName is the optional name of the schema.
	SchemaName string

	// SchemaDescription is the optional description of the schema.
	SchemaDescription string

	// IsEnabled indicates whether telemetry is enabled.
	IsEnabled *bool

	// RecordInputs indicates whether to record inputs in telemetry.
	RecordInputs *bool

	// RecordOutputs indicates whether to record outputs in telemetry.
	RecordOutputs *bool

	// FunctionID is the identifier from telemetry settings for grouping related operations.
	FunctionID string

	// Metadata is additional metadata from telemetry settings.
	Metadata map[string]interface{}
}

// ObjectOnStepStartEvent is fired just before the provider is called.
// For object generation, there is always exactly one step (step 0).
//
// Note on cancellation: the TypeScript SDK includes an abortSignal field on this
// event. In Go, the ctx parameter passed to the callback serves this role —
// pass ctx to any operations that should respect cancellation.
type ObjectOnStepStartEvent struct {
	// CallID correlates this event with the other events for this call.
	CallID string

	// StepNumber is always 0 for object generation.
	StepNumber int

	// Provider is the provider identifier.
	Provider string

	// ModelID is the specific model identifier.
	ModelID string

	// ProviderOptions are additional provider-specific options.
	ProviderOptions map[string]interface{}

	// Headers are additional HTTP headers sent with the request.
	Headers map[string]string

	// PromptMessages is the prompt in provider format, as built from the
	// user-supplied prompt/messages/system options. Mirrors the TS SDK's
	// promptMessages field on ObjectOnStepStartEvent (used for telemetry).
	PromptMessages *types.Prompt

	// FunctionID is the identifier from telemetry settings.
	FunctionID string

	// Metadata is additional metadata from telemetry settings.
	Metadata map[string]interface{}
}

// ObjectOnStepFinishEvent is fired after the provider returns but BEFORE JSON parsing
// and schema validation. Carries the raw model output.
type ObjectOnStepFinishEvent struct {
	// CallID correlates this event with the other events for this call.
	CallID string

	// StepNumber is always 0 for object generation.
	StepNumber int

	// Provider is the provider identifier.
	Provider string

	// ModelID is the specific model identifier.
	ModelID string

	// FinishReason is the unified reason why generation finished.
	FinishReason types.FinishReason

	// Usage is the token consumption for this step.
	Usage types.Usage

	// ObjectText is the raw text output from the model, before JSON parsing.
	ObjectText string

	// Reasoning is the reasoning generated by the model, if any.
	Reasoning string

	// Warnings are warnings from the model provider.
	Warnings []types.Warning

	// Request contains additional information about the request sent to the provider.
	// Mirrors ObjectOnStepFinishEvent.request in the TypeScript SDK.
	Request GenerateStepRequest

	// Response contains additional information about the response from the provider.
	// Mirrors ObjectOnStepFinishEvent.response in the TypeScript SDK.
	Response GenerateStepResponse

	// ProviderMetadata holds provider-specific metadata.
	ProviderMetadata map[string]interface{}

	// FunctionID is the identifier from telemetry settings.
	FunctionID string

	// Metadata is additional metadata from telemetry settings.
	Metadata map[string]interface{}
}

// ObjectOnFinishEvent is fired when the entire operation completes, including
// JSON parsing and schema validation. For GenerateObject, Error is always nil
// (errors are returned instead). For StreamObject, Error may be set if
// parsing or validation failed, in which case Object will be nil.
type ObjectOnFinishEvent struct {
	// CallID correlates this event with the other events for this call.
	CallID string

	// Object is the generated and parsed output.
	// Always set for GenerateObject. May be nil for StreamObject when parsing fails.
	Object interface{}

	// Error contains parse or validation errors, if any.
	// Always nil for GenerateObject. May be set for StreamObject.
	Error error

	// Reasoning is the reasoning generated by the model, if any.
	Reasoning string

	// FinishReason is the unified reason why generation finished.
	FinishReason types.FinishReason

	// Usage is the total token consumption.
	Usage types.Usage

	// Warnings are warnings from the model provider.
	Warnings []types.Warning

	// Request contains additional information about the request sent to the provider.
	// Mirrors ObjectOnFinishEvent.request in the TypeScript SDK.
	Request GenerateStepRequest

	// Response contains additional information about the response from the provider.
	// Mirrors ObjectOnFinishEvent.response in the TypeScript SDK.
	Response GenerateStepResponse

	// ProviderMetadata holds provider-specific metadata.
	ProviderMetadata map[string]interface{}

	// FunctionID is the identifier from telemetry settings.
	FunctionID string

	// Metadata is additional metadata from telemetry settings.
	Metadata map[string]interface{}
}
