package harness

import (
	"context"
	"encoding/json"
	"os"
	"reflect"
	"regexp"
	"strings"
	"testing"

	"github.com/digitallysavvy/go-ai/pkg/providerutils"
)

var hex16 = regexp.MustCompile(`^[0-9a-f]{16}$`)

var baseRecipe = Bootstrap{
	HarnessID:    "demo",
	BootstrapDir: "/tmp/harness/demo",
	Files: []BootstrapFile{
		{Path: "/tmp/harness/demo/a.txt", Content: "one"},
		{Path: "/tmp/harness/demo/b.txt", Content: "two"},
	},
	Commands: []BootstrapCommand{{Command: "echo first"}, {Command: "echo second"}},
}

const testStateDirectory = "/work"

// identity_fixtures.json is generated by testdata/gen_identity_fixtures.mjs,
// which runs the verbatim TS hashing code under Node.
type identityFixtures struct {
	Recipes []struct {
		Recipe   Bootstrap `json:"recipe"`
		Identity string    `json:"identity"`
	} `json:"recipes"`
	SandboxIdentities []struct {
		Input struct {
			RecipeIdentity string `json:"recipeIdentity"`
			BootstrapHash  string `json:"bootstrapHash"`
			WorkDir        string `json:"workDir"`
		} `json:"input"`
		Identity string `json:"identity"`
	} `json:"sandboxIdentities"`
	PreparedIdentities []struct {
		Input struct {
			RecipeIdentities map[string]string `json:"recipeIdentities"`
			BootstrapHash    string            `json:"bootstrapHash"`
			WorkDir          string            `json:"workDir"`
		} `json:"input"`
		Identity string `json:"identity"`
	} `json:"preparedIdentities"`
}

func loadIdentityFixtures(t *testing.T) identityFixtures {
	t.Helper()
	data, err := os.ReadFile("testdata/identity_fixtures.json")
	if err != nil {
		t.Fatal(err)
	}
	var f identityFixtures
	if err := json.Unmarshal(data, &f); err != nil {
		t.Fatal(err)
	}
	return f
}

func TestBootstrapIdentityParityWithTS(t *testing.T) {
	f := loadIdentityFixtures(t)
	for _, tc := range f.Recipes {
		if got := HashHarnessBootstrap(tc.Recipe); got != tc.Identity {
			t.Errorf("HashHarnessBootstrap(%s) = %s, want TS %s", tc.Recipe.HarnessID, got, tc.Identity)
		}
	}
	for _, tc := range f.SandboxIdentities {
		got := hashSandboxBootstrapIdentity(tc.Input.RecipeIdentity, tc.Input.BootstrapHash, tc.Input.WorkDir)
		if got != tc.Identity {
			t.Errorf("hashSandboxBootstrapIdentity(%+v) = %s, want TS %s", tc.Input, got, tc.Identity)
		}
	}
	for _, tc := range f.PreparedIdentities {
		got := resolvePreparedSandboxIdentity(tc.Input.RecipeIdentities, tc.Input.BootstrapHash, tc.Input.WorkDir)
		if got != tc.Identity {
			t.Errorf("resolvePreparedSandboxIdentity(%+v) = %s, want TS %s", tc.Input, got, tc.Identity)
		}
	}
}

// TS: hashHarnessBootstrap "includes the harness state directory in the recipe identity".
func TestHashHarnessBootstrapInlineSnapshot(t *testing.T) {
	if got := HashHarnessBootstrap(baseRecipe); got != "2b1b95adf78b2953" {
		t.Fatalf("got %s", got)
	}
}

func TestHashHarnessBootstrap(t *testing.T) {
	base := HashHarnessBootstrap(baseRecipe)
	if !hex16.MatchString(base) || HashHarnessBootstrap(baseRecipe) != base {
		t.Fatalf("not a deterministic 16-char hex id: %s", base)
	}
	reordered := baseRecipe
	reordered.Files = []BootstrapFile{baseRecipe.Files[1], baseRecipe.Files[0]}
	if HashHarnessBootstrap(reordered) != base {
		t.Error("file ordering must not affect the hash")
	}
	mutations := map[string]func(b *Bootstrap){
		"file content": func(b *Bootstrap) {
			b.Files = []BootstrapFile{{Path: "/tmp/harness/demo/a.txt", Content: "one!"}, baseRecipe.Files[1]}
		},
		"command":      func(b *Bootstrap) { b.Commands = []BootstrapCommand{{Command: "echo different"}} },
		"harnessId":    func(b *Bootstrap) { b.HarnessID = "other" },
		"bootstrapDir": func(b *Bootstrap) { b.BootstrapDir = "/tmp/other" },
	}
	for name, mutate := range mutations {
		altered := baseRecipe
		mutate(&altered)
		if HashHarnessBootstrap(altered) == base {
			t.Errorf("hash must change when %s changes", name)
		}
	}
	if BootstrapSchemaVersion <= 0 {
		t.Fatal("BootstrapSchemaVersion must be positive")
	}
}

func TestBootstrapMarkerPath(t *testing.T) {
	if got := BootstrapMarkerPath(baseRecipe, "abc1234567890def", testStateDirectory); got != "/tmp/harness/demo/.bootstrap-abc1234567890def.ok" {
		t.Fatal(got)
	}
	rel := baseRecipe
	rel.BootstrapDir = ".harness-bootstrap/demo"
	if got := BootstrapMarkerPath(rel, "abc1234567890def", testStateDirectory); got != "/work/.harness-bootstrap/demo/.bootstrap-abc1234567890def.ok" {
		t.Fatal(got)
	}
}

func TestApplyBootstrapRecipe(t *testing.T) {
	const identity = "idtest1234567890"
	ctx := context.Background()
	marker := BootstrapMarkerPath(baseRecipe, identity, testStateDirectory)

	t.Run("skips when the marker file is present", func(t *testing.T) {
		sb := newMockSandbox()
		sb.files[marker] = ""
		if err := ApplyBootstrapRecipe(ctx, sb, baseRecipe, identity, testStateDirectory); err != nil {
			t.Fatal(err)
		}
		if len(sb.reads) != 1 || len(sb.writes) != 0 || len(sb.runs) != 0 {
			t.Fatalf("reads=%d writes=%d runs=%d", len(sb.reads), len(sb.writes), len(sb.runs))
		}
	})

	t.Run("creates the directory, writes files, runs commands there, writes the marker", func(t *testing.T) {
		sb := newMockSandbox()
		if err := ApplyBootstrapRecipe(ctx, sb, baseRecipe, identity, testStateDirectory); err != nil {
			t.Fatal(err)
		}
		if len(sb.writes) != len(baseRecipe.Files)+1 || len(sb.runs) != len(baseRecipe.Commands)+1 {
			t.Fatalf("writes=%d runs=%d", len(sb.writes), len(sb.runs))
		}
		first := sb.runs[0]
		if first.Command != `mkdir -p "$BOOTSTRAP_DIR"` || !reflect.DeepEqual(first.Env, map[string]string{"BOOTSTRAP_DIR": "/tmp/harness/demo"}) || first.WorkingDirectory != "" {
			t.Fatalf("first run = %+v", first)
		}
		wds := []string{sb.runs[0].WorkingDirectory, sb.runs[1].WorkingDirectory, sb.runs[2].WorkingDirectory}
		if !reflect.DeepEqual(wds, []string{"", "/tmp/harness/demo", "/tmp/harness/demo"}) {
			t.Fatalf("working dirs = %q", wds)
		}
		if sb.indexOfEvent("run:") > sb.indexOfEvent("write:") {
			t.Fatal("mkdir must run before the first write")
		}
		if last := sb.writes[len(sb.writes)-1]; last.Path != marker {
			t.Fatalf("last write = %s", last.Path)
		}
	})

	t.Run("resolves relative paths and runs commands from the bootstrap directory", func(t *testing.T) {
		rel := Bootstrap{
			HarnessID:    "demo",
			BootstrapDir: ".harness-bootstrap/demo",
			Files:        []BootstrapFile{{Path: ".harness-bootstrap/demo/file.txt", Content: "content"}},
			Commands:     []BootstrapCommand{{Command: "echo first"}, {Command: "echo second"}},
		}
		sb := newMockSandbox()
		if err := ApplyBootstrapRecipe(ctx, sb, rel, identity, testStateDirectory); err != nil {
			t.Fatal(err)
		}
		if sb.reads[0] != "/work/.harness-bootstrap/demo/.bootstrap-idtest1234567890.ok" {
			t.Fatal(sb.reads[0])
		}
		paths := []string{sb.writes[0].Path, sb.writes[1].Path}
		if !reflect.DeepEqual(paths, []string{"/work/.harness-bootstrap/demo/file.txt", "/work/.harness-bootstrap/demo/.bootstrap-idtest1234567890.ok"}) {
			t.Fatal(paths)
		}
		if sb.runs[1].WorkingDirectory != "/work/.harness-bootstrap/demo" {
			t.Fatal(sb.runs[1].WorkingDirectory)
		}
	})

	t.Run("throws when a command exits non-zero and skips the marker write", func(t *testing.T) {
		sb := newMockSandbox()
		sb.runFn = func(opts providerutils.SandboxProcessOptions) providerutils.SandboxRunResult {
			if opts.Command == `mkdir -p "$BOOTSTRAP_DIR"` {
				return providerutils.SandboxRunResult{Stdout: "ok", Stderr: "boom"}
			}
			return providerutils.SandboxRunResult{ExitCode: 7, Stdout: "ok", Stderr: "boom"}
		}
		err := ApplyBootstrapRecipe(ctx, sb, baseRecipe, identity, testStateDirectory)
		if err == nil || !regexp.MustCompile(`(?s)Bootstrap command failed.*exit 7.*boom`).MatchString(err.Error()) {
			t.Fatalf("err = %v", err)
		}
		if len(sb.runs) != 2 {
			t.Fatalf("runs = %d", len(sb.runs))
		}
		if _, ok := sb.files[marker]; ok {
			t.Fatal("marker must not be written")
		}
	})

	t.Run("stops before writing files when bootstrap directory creation fails", func(t *testing.T) {
		sb := newMockSandbox()
		sb.runFn = func(providerutils.SandboxProcessOptions) providerutils.SandboxRunResult {
			return providerutils.SandboxRunResult{ExitCode: 9, Stdout: "ok", Stderr: "mkdir failed"}
		}
		err := ApplyBootstrapRecipe(ctx, sb, baseRecipe, identity, testStateDirectory)
		if err == nil || !regexp.MustCompile(`(?s)Failed to create bootstrap directory.*exit 9.*mkdir failed`).MatchString(err.Error()) {
			t.Fatalf("err = %v", err)
		}
		if len(sb.runs) != 1 || len(sb.writes) != 0 {
			t.Fatal("must stop after mkdir failure")
		}
	})
}

var sbRecipe = Bootstrap{
	HarnessID:    "demo",
	BootstrapDir: ".harness-bootstrap/demo",
	Files:        []BootstrapFile{{Path: ".harness-bootstrap/demo/a.txt", Content: "one"}},
	Commands:     []BootstrapCommand{{Command: "echo ok"}},
}

func noopBootstrap(context.Context, SandboxBootstrapContext) error { return nil }

func TestValidateSandboxBootstrapSettings(t *testing.T) {
	if err := ValidateSandboxBootstrapSettings(SandboxConfig{OnBootstrap: noopBootstrap}); err == nil || !strings.Contains(err.Error(), "must be provided together") {
		t.Fatal(err)
	}
	if err := ValidateSandboxBootstrapSettings(SandboxConfig{BootstrapHash: "hash"}); err == nil || !strings.Contains(err.Error(), "must be provided together") {
		t.Fatal(err)
	}
	// TS uses '' as an invalid value too; Go's zero value means "unset", so
	// the empty case is covered by NormalizeSandboxWorkDir directly.
	if _, err := NormalizeSandboxWorkDir(""); err == nil {
		t.Fatal("empty workDir must be rejected")
	}
	for _, v := range []string{".", "/repo", "../repo", "repo/../../x", `a\b`, "a\x00b"} {
		if err := ValidateSandboxBootstrapSettings(SandboxConfig{WorkDir: v}); err == nil || !strings.Contains(err.Error(), "workDir") {
			t.Errorf("workDir %q: err = %v", v, err)
		}
	}
	for in, want := range map[string]string{"repo/../ai-sdk": "ai-sdk", "./ai-sdk": "ai-sdk"} {
		if got, err := NormalizeSandboxWorkDir(in); err != nil || got != want {
			t.Errorf("NormalizeSandboxWorkDir(%q) = %q, %v", in, got, err)
		}
	}
}

func TestCreateSandboxBootstrapPlan(t *testing.T) {
	plan, err := CreateSandboxBootstrapPlan(&sbRecipe, SandboxConfig{})
	if err != nil || plan.Identity != HashHarnessBootstrap(sbRecipe) {
		t.Fatalf("plan identity = %s, %v", plan.Identity, err)
	}
	a, _ := CreateSandboxBootstrapPlan(&sbRecipe, SandboxConfig{BootstrapHash: "repo-v1", OnBootstrap: noopBootstrap})
	b, _ := CreateSandboxBootstrapPlan(&sbRecipe, SandboxConfig{BootstrapHash: "repo-v2", OnBootstrap: noopBootstrap})
	if a.Identity == b.Identity {
		t.Error("identity must change with bootstrapHash")
	}
	c, _ := CreateSandboxBootstrapPlan(&sbRecipe, SandboxConfig{WorkDir: "repo-a"})
	d, _ := CreateSandboxBootstrapPlan(&sbRecipe, SandboxConfig{WorkDir: "repo-b"})
	if c.Identity == d.Identity {
		t.Error("identity must change with workDir")
	}
	none, _ := CreateSandboxBootstrapPlan(nil, SandboxConfig{})
	if none.Identity != "" || none.OnFirstCreate != nil {
		t.Error("no recipe and no caller bootstrap => empty plan")
	}
}

func TestResolveSessionWorkDir(t *testing.T) {
	cases := []struct{ harnessID, sessionID, workDir, want string }{
		{"mock", "s1", "", "/work/mock-s1"},
		{"mock", "../../../../project", "", "/work/mock-..%2F..%2F..%2F..%2Fproject"},
		{"../mock", "s1", "", "/work/..%2Fmock-s1"},
		{"mock", "s1", "ai-sdk", "/work/ai-sdk"},
	}
	for _, tc := range cases {
		if got := ResolveSessionWorkDir("/work", tc.harnessID, tc.sessionID, tc.workDir); got != tc.want {
			t.Errorf("got %s, want %s", got, tc.want)
		}
	}
}

func TestRunSandboxBootstrap(t *testing.T) {
	ctx := context.Background()
	t.Run("runs built-in bootstrap before caller bootstrap", func(t *testing.T) {
		sb := newMockSandbox()
		var got SandboxBootstrapContext
		calledAfter := -1
		err := RunSandboxBootstrap(ctx, RunSandboxBootstrapOptions{
			Session:        sb,
			Recipe:         &sbRecipe,
			RecipeIdentity: HashHarnessBootstrap(sbRecipe),
			WorkDir:        "ai-sdk",
			OnBootstrap: func(_ context.Context, bc SandboxBootstrapContext) error {
				got = bc
				calledAfter = len(sb.runs)
				return nil
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		if got.WorkDir != "/work/ai-sdk" || got.Session != sb {
			t.Fatalf("onBootstrap ctx = %+v", got)
		}
		want := []string{`printf "%s" "$HOME"`, `mkdir -p "$BOOTSTRAP_DIR"`, "echo ok", "pwd", `mkdir -p "$WORK_DIR"`}
		if cmds := sb.runCommands(); !reflect.DeepEqual(cmds, want) {
			t.Fatalf("commands = %q", cmds)
		}
		if !regexp.MustCompile(`^/home/agent/\.ai-sdk-harness/\.harness-bootstrap/demo/\.bootstrap-[0-9a-f]{16}\.ok$`).MatchString(sb.reads[0]) {
			t.Fatal(sb.reads[0])
		}
		if sb.writes[0] != (providerutils.SandboxWriteTextFileOptions{Path: "/home/agent/.ai-sdk-harness/.harness-bootstrap/demo/a.txt", Content: "one"}) {
			t.Fatalf("write = %+v", sb.writes[0])
		}
		if calledAfter < 3 {
			t.Fatal("recipe commands must run before the caller bootstrap")
		}
	})

	t.Run("uses the default cwd for caller bootstrap when workDir is absent", func(t *testing.T) {
		sb := newMockSandbox()
		var workDir string
		err := RunSandboxBootstrap(ctx, RunSandboxBootstrapOptions{
			Session: sb,
			OnBootstrap: func(_ context.Context, bc SandboxBootstrapContext) error {
				workDir = bc.WorkDir
				return nil
			},
		})
		if err != nil || workDir != "/work" {
			t.Fatalf("workDir = %q, %v", workDir, err)
		}
	})

	// 31742b9a1b: onBootstrap marker mechanism.
	t.Run("skips onBootstrap when the marker for bootstrapHash already exists", func(t *testing.T) {
		sb := newMockSandbox()
		calls := 0
		opts := RunSandboxBootstrapOptions{
			Session: sb,
			OnBootstrap: func(context.Context, SandboxBootstrapContext) error {
				calls++
				return nil
			},
			BootstrapHash:           "hash-1",
			SkipOnBootstrapIfMarked: true,
		}
		if err := RunSandboxBootstrap(ctx, opts); err != nil {
			t.Fatal(err)
		}
		if calls != 1 {
			t.Fatalf("first call: onBootstrap called %d times, want 1", calls)
		}
		if err := RunSandboxBootstrap(ctx, opts); err != nil {
			t.Fatal(err)
		}
		if calls != 1 {
			t.Fatalf("second call: onBootstrap called %d times, want 1 (marker should skip it)", calls)
		}
	})

	t.Run("does not write a marker when skipOnBootstrapIfMarked is false", func(t *testing.T) {
		sb := newMockSandbox()
		calls := 0
		opts := RunSandboxBootstrapOptions{
			Session: sb,
			OnBootstrap: func(context.Context, SandboxBootstrapContext) error {
				calls++
				return nil
			},
			BootstrapHash: "hash-2",
		}
		if err := RunSandboxBootstrap(ctx, opts); err != nil {
			t.Fatal(err)
		}
		marked, err := HasOnBootstrapMarker(ctx, sb, "hash-2")
		if err != nil {
			t.Fatal(err)
		}
		if !marked {
			t.Fatal("marker should still be written after a successful OnBootstrap, regardless of SkipOnBootstrapIfMarked")
		}
		if err := RunSandboxBootstrap(ctx, RunSandboxBootstrapOptions{
			Session: sb, OnBootstrap: opts.OnBootstrap, BootstrapHash: "hash-2",
		}); err != nil {
			t.Fatal(err)
		}
		if calls != 2 {
			t.Fatalf("onBootstrap called %d times, want 2 (SkipOnBootstrapIfMarked false must not consult the marker)", calls)
		}
	})
}

func TestStateDirectoryPaths(t *testing.T) {
	if got := StateDirectoryPath("/home/agent"); got != "/home/agent/.ai-sdk-harness" {
		t.Fatal(got)
	}
	if got := StateDirectoryPath("$HOME"); got != "$HOME/.ai-sdk-harness" {
		t.Fatal(got)
	}
	const stateDir = "/home/agent/.ai-sdk-harness"
	if got := SessionDataDirectoryPath(stateDir, "s1-abc"); got != stateDir+"/.agent-runs/s1-abc" {
		t.Fatal(got)
	}
	cases := [][2]string{
		{"../../../../work/project", "..%2F..%2F..%2F..%2Fwork%2Fproject"},
		{"/work/project", "%2Fwork%2Fproject"},
		{"..", "%2E%2E"},
		{".", "%2E"},
		{"", "%"},
		{"%", "%25"},
		{"a/b", "a%2Fb"},
		{"a%2Fb", "a%252Fb"},
		{`a\..`, "a%5C.."},
		{"a\x00b", "a%00b"},
	}
	for _, tc := range cases {
		dir := SessionDataDirectoryPath(stateDir, tc[0])
		if dir != stateDir+"/.agent-runs/"+tc[1] {
			t.Errorf("session %q => %s", tc[0], dir)
		}
	}
}

func TestResolveSandboxHomeDir(t *testing.T) {
	sb := newMockSandbox()
	sb.runFn = func(providerutils.SandboxProcessOptions) providerutils.SandboxRunResult {
		return providerutils.SandboxRunResult{Stdout: "/home/vercel-sandbox\n"}
	}
	if got, err := ResolveSandboxHomeDir(context.Background(), sb); err != nil || got != "/home/vercel-sandbox" {
		t.Fatal(got, err)
	}
	sb.runFn = func(providerutils.SandboxProcessOptions) providerutils.SandboxRunResult {
		return providerutils.SandboxRunResult{Stdout: "home/user"}
	}
	if _, err := ResolveSandboxHomeDir(context.Background(), sb); err == nil || !strings.Contains(err.Error(), "Unable to resolve sandbox HOME directory") {
		t.Fatal(err)
	}
}

func TestResolveSandboxDefaultWorkingDirectory(t *testing.T) {
	sb := newMockSandbox()
	sb.runFn = func(providerutils.SandboxProcessOptions) providerutils.SandboxRunResult {
		return providerutils.SandboxRunResult{Stdout: "/work//\n"}
	}
	if got, _ := ResolveSandboxDefaultWorkingDirectory(context.Background(), sb); got != "/work" {
		t.Fatal(got)
	}
	net := &mockNetworkSandbox{mockSandbox: newMockSandbox()}
	if got, _ := ResolveSandboxDefaultWorkingDirectory(context.Background(), net); got != "/work" || len(net.runs) != 0 {
		t.Fatal("network sessions use DefaultWorkingDirectory without running pwd")
	}
	if GetRestrictedSandboxSession(net) != providerutils.SandboxSession(net.mockSandbox) {
		t.Fatal("restricted view expected")
	}
}
