import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'doc',
      id: 'introduction/index',
      label: 'Introduction',
    },
    {
      type: 'doc',
      id: 'announcing-go-ai/index',
      label: "What's New",
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: '02-getting-started' }],
    },
    {
      type: 'category',
      label: 'Foundations',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: '02-foundations' }],
    },
    {
      type: 'category',
      label: 'Core API',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: '03-ai-sdk-core' }],
    },
    {
      type: 'category',
      label: 'Agents',
      items: [{ type: 'autogenerated', dirName: '03-agents' }],
    },
    {
      type: 'category',
      label: 'Providers',
      items: [
        { type: 'autogenerated', dirName: '05-providers' },
        {
          type: 'category',
          label: 'Provider Guides',
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'providers' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'Advanced',
      items: [
        { type: 'autogenerated', dirName: '06-advanced' },
        { type: 'autogenerated', dirName: '04-advanced' },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'guides' }],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        { type: 'autogenerated', dirName: '07-reference' },
        { type: 'autogenerated', dirName: 'reference' },
      ],
    },
    {
      type: 'category',
      label: 'Migration',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: '08-migration-guides' }],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: '09-troubleshooting' }],
    },
    {
      type: 'category',
      label: 'Security',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'security' }],
    },
  ],
};

export default sidebars;
