import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'doc',
      id: 'introduction/index',
      label: 'Introduction',
    },
    {
      type: 'doc',
      id: 'announcing-go-ai/index',
      label: "What's New",
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: '02-getting-started' }],
    },
    {
      type: 'category',
      label: 'Build a chat app',
      collapsed: false,
      link: { type: 'doc', id: 'build-a-chat-app/index' },
      items: [
        'build-a-chat-app/serve-usechat-from-go',
        'build-a-chat-app/tool-approval',
        'build-a-chat-app/coding-agents-harness',
      ],
    },
    {
      type: 'category',
      label: 'Recipes',
      collapsed: true,
      link: { type: 'doc', id: 'recipes/index' },
      items: [
        'recipes/usechat-backend',
        'recipes/tool-approval',
        'recipes/mcp-tools',
        'recipes/structured-output',
        'recipes/switch-providers',
        'recipes/claude-reasoning',
        'recipes/harness-coding-agent',
        'recipes/rag-embeddings',
        'recipes/rate-limits-retries',
        'recipes/mock-model-tests',
        'recipes/agent-with-tools',
        'recipes/stream-text',
      ],
    },
    {
      type: 'category',
      label: 'Foundations',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: '02-foundations' }],
    },
    {
      type: 'category',
      label: 'Core API',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: '03-ai-sdk-core' }],
    },
    {
      type: 'category',
      label: 'Agents',
      items: [{ type: 'autogenerated', dirName: '03-agents' }],
    },
    {
      type: 'category',
      label: 'Providers',
      items: [
        { type: 'autogenerated', dirName: '05-providers' },
        {
          type: 'category',
          label: 'Provider Guides',
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'providers' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'Advanced',
      items: [
        { type: 'autogenerated', dirName: '06-advanced' },
        { type: 'autogenerated', dirName: '04-advanced' },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'guides' }],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        { type: 'autogenerated', dirName: '07-reference' },
        { type: 'autogenerated', dirName: 'reference' },
      ],
    },
    {
      type: 'category',
      label: 'Migration',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: '08-migration-guides' }],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: '09-troubleshooting' }],
    },
    {
      type: 'category',
      label: 'Security',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'security' }],
    },
    {
      // Generated from the root CHANGELOG.md by scripts/sync-changelog.mjs.
      type: 'doc',
      id: 'changelog/index',
      label: 'Changelog',
    },
  ],
};

export default sidebars;
