// Package modelcatalog provides maintainer-triggered model ID refresh helpers.
package modelcatalog

import (
	"bytes"
	"context"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
)

// ModelID describes a provider model identifier and optional Go constant name.
type ModelID struct {
	ID        string
	ConstName string
}

// ModelCatalogRefresher fetches a provider's current model catalog.
type ModelCatalogRefresher interface {
	Fetch(ctx context.Context) ([]ModelID, error)
}

// WriteModelIDsGo writes a formatted Go source file containing model ID constants.
func WriteModelIDsGo(path, packageName, header string, models []ModelID) error {
	src, err := RenderModelIDsGo(packageName, header, models)
	if err != nil {
		return err
	}
	return os.WriteFile(path, src, 0o644)
}

// RenderModelIDsGo renders model ID constants as valid gofmt-formatted Go code.
func RenderModelIDsGo(packageName, header string, models []ModelID) ([]byte, error) {
	if packageName == "" {
		return nil, fmt.Errorf("package name is required")
	}

	cleaned := make([]ModelID, 0, len(models))
	seen := make(map[string]struct{}, len(models))
	for _, model := range models {
		if model.ID == "" {
			continue
		}
		if _, ok := seen[model.ID]; ok {
			continue
		}
		seen[model.ID] = struct{}{}
		if model.ConstName == "" {
			model.ConstName = ConstNameFromModelID(model.ID)
		}
		cleaned = append(cleaned, model)
	}
	sort.Slice(cleaned, func(i, j int) bool {
		return cleaned[i].ID < cleaned[j].ID
	})

	var b bytes.Buffer
	b.WriteString("// Code generated by model catalog refresh; DO NOT EDIT.\n")
	if header != "" {
		for _, line := range strings.Split(header, "\n") {
			if strings.TrimSpace(line) != "" {
				b.WriteString("// " + line + "\n")
			}
		}
	}
	b.WriteString("package " + packageName + "\n\n")
	b.WriteString("const (\n")
	for _, model := range cleaned {
		fmt.Fprintf(&b, "\t%s = %q\n", model.ConstName, model.ID)
	}
	b.WriteString(")\n")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return nil, err
	}
	return formatted, nil
}

// ConstNameFromModelID converts a model ID to an exported Go constant name.
func ConstNameFromModelID(id string) string {
	var b strings.Builder
	b.WriteString("Model")
	upperNext := true
	for _, r := range id {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			if upperNext && r >= 'a' && r <= 'z' {
				r -= 'a' - 'A'
			}
			b.WriteRune(r)
			upperNext = false
			continue
		}
		upperNext = true
	}
	if b.Len() == len("Model") {
		return "ModelID"
	}
	return b.String()
}
